-- ESTO ES PARA SELECCIONAR LAS AREAS
Select * from AREAS;

-- ESTO ES PARA VER LA AREA
SELECT B.ID,B.NOMBRE AS SUB_VISTA, A.NOMBRE AS AREA FROM SUB_VISTAS AS B
LEFT JOIN AREAS AS A
ON B.ID_AREA = A.ID
WHERE A.NOMBRE = "Logistica:"
;

-- ESTO ES PARA INSERTAR NUEVA AREA 
INSERT INTO SUB_VISTAS(NOMBRE, ID_AREA) VALUES ("LISTADO DE MOVILIDAD",7);

-- ESTO ES PARA CAMBIAR EL NOMBRE DE LA SUBVISTA
UPDATE SUB_VISTAS SET NOMBRE = "LISTADO DE ARCHIVOS SUBIDOS" where ID = 72;

-- HASTA ACA

SELECT * FROM SUB_VISTAS;