-- TABLA POSIBLES CLIENTES ANIDADA A LA TABLA HISTORIAL_COTIZACION
CREATE TABLE posibles_clientes (
    ID_POSIBLE INT AUTO_INCREMENT PRIMARY KEY,
    ID_COTI_REF INT, -- Para vincular con historial_cotizacion
    COD_COTIZACION_REF VARCHAR(50),
    FECHA DATETIME,
    NOMBRE_CLIENTE VARCHAR(150),
    CEL VARCHAR(20),
    RUC VARCHAR(11),
    DNI VARCHAR(8),
    REGION VARCHAR(100),
    DISTRITO VARCHAR(100),
    PRODUCTO_INTERESADO VARCHAR(255),
    CAMPANIA VARCHAR(20),
    OBSERVACIONES VARCHAR(255) DEFAULT 'REALIZO COTIZACION',
    ESTADO ENUM('PENDIENTE', 'CLIENTE', 'CLIENTE PERDIDO'),
    FOREIGN KEY (ID_COTI_REF) REFERENCES historial_cotizacion(ID_COTI)
);
--
