USE Zeus_Safety_Data_Integration;

CREATE TABLE IF NOT EXISTS FRANJA_PRECIOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
CODIGO VARCHAR(30) REFERENCES productos(CODIGO),
UNIDAD_MEDIDA_VENTA ENUM('DOCENA','UNIDAD','CAJA','PAR') NOT NULL,
CANTIDAD_UNIDAD_MEDIDA_VENTA INT NOT NULL,
PRECIO_UNIDAD_MEDIDA_VENTA DOUBLE NOT NULL,
UNIDAD_MEDIDA_CAJA ENUM('DOCENA','UNIDAD','CAJA','PAR') NOT NULL,
CANTIDAD_CAJA INT NOT NULL,
CLASIFICACION VARCHAR(30),
TEXTO_COPIAR TEXT NOT NULL
);
SELECT * FROM FRANJA_PRECIOS
LIMIT 50;
-- SET SQL_SAFE_UPDATES = 0;
-- UPDATE FRANJA_PRECIOS SET UNIDAD_MEDIDA_VENTA = "CAJA" WHERE UNIDAD_MEDIDA_VENTA="UNIDAD";
-- SET SQL_SAFE_UPDATES = 1;


--Para insertar precios en la tabla FRANJA_PRECIOS
DELIMITER $$

CREATE PROCEDURE insertar_franja_precios(
    IN IN_CODIGO VARCHAR(30),
    IN IN_UNIDAD_MEDIDA_VENTA VARCHAR(20),
    IN IN_CANTIDAD_UMV INT,
    IN IN_PRECIO DOUBLE,
    IN IN_UNIDAD_MEDIDA_CAJA VARCHAR(20),
    IN IN_CANTIDAD_CAJA INT,
    IN IN_CLASIFICACION VARCHAR(30),
    IN IN_TEXTO TEXT
)
BEGIN
    INSERT INTO FRANJA_PRECIOS(
        CODIGO, 
        UNIDAD_MEDIDA_VENTA,
        CANTIDAD_UNIDAD_MEDIDA_VENTA,
        PRECIO_UNIDAD_MEDIDA_VENTA,
        UNIDAD_MEDIDA_CAJA,
        CANTIDAD_CAJA,
        CLASIFICACION,
        TEXTO_COPIAR
    ) VALUES (
        IN_CODIGO,
        IN_UNIDAD_MEDIDA_VENTA,
        IN_CANTIDAD_UMV,
        IN_PRECIO,
        IN_UNIDAD_MEDIDA_CAJA,
        IN_CANTIDAD_CAJA,
        IN_CLASIFICACION,
        IN_TEXTO
    );
END $$

DELIMITER ;

--para actualizar precios en la tabla FRANJA_PRECIOS
DELIMITER $$

CREATE PROCEDURE actualizar_franja_precios(
    IN IN_ID INT,
    IN IN_PRECIO DOUBLE,
    IN IN_CANTIDAD_UMV INT,
    IN IN_CANTIDAD_CAJA INT,
    IN IN_TEXTO TEXT
)
BEGIN
    UPDATE FRANJA_PRECIOS
    SET 
        PRECIO_UNIDAD_MEDIDA_VENTA = IN_PRECIO,
        CANTIDAD_UNIDAD_MEDIDA_VENTA = IN_CANTIDAD_UMV,
        CANTIDAD_CAJA = IN_CANTIDAD_CAJA,
        TEXTO_COPIAR = IN_TEXTO
    WHERE ID = IN_ID;
END $$

DELIMITER ;

--para eliminar una franja de precios en la tabla FRANJA_PRECIOS
DELIMITER $$

CREATE PROCEDURE eliminar_franja_precios(IN IN_ID INT)
BEGIN
    DELETE FROM FRANJA_PRECIOS WHERE ID = IN_ID;
END $$

DELIMITER ;