USE Zeus_Safety_Data_Integration;

CREATE TABLE IF NOT EXISTS FRANJA_PRECIOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
CODIGO VARCHAR(30) REFERENCES productos(CODIGO),
UNIDAD_MEDIDA_VENTA ENUM('DOCENA','UNIDAD','CAJA','PAR') NOT NULL,
CANTIDAD_UNIDAD_MEDIDA_VENTA INT NOT NULL,
PRECIO_UNIDAD_MEDIDA_VENTA DOUBLE NOT NULL,
UNIDAD_MEDIDA_CAJA ENUM('DOCENA','UNIDAD','CAJA','PAR') NOT NULL,
CANTIDAD_CAJA INT NOT NULL,
CLASIFICACION VARCHAR(30),
TEXTO_COPIAR TEXT NOT NULL
);
SELECT * FROM FRANJA_PRECIOS
LIMIT 50;
SET SQL_SAFE_UPDATES = 0;
UPDATE FRANJA_PRECIOS SET UNIDAD_MEDIDA_VENTA = "CAJA" WHERE UNIDAD_MEDIDA_VENTA="UNIDAD";
SET SQL_SAFE_UPDATES = 1;
#######################################
#######################################
#######################################
DROP PROCEDURE IF EXISTS FRANJA_PRECIOS;
DELIMITER $$;
CREATE PROCEDURE FRANJA_PRECIOS(IN METHOD VARCHAR(30))
BEGIN
	IF METHOD = "MALVINAS" THEN
		SELECT F.ID, F.CODIGO, P.NOMBRE,
        CONCAT(UNIDAD_MEDIDA_CAJA," ",CANTIDAD_CAJA) AS CANTIDAD_CAJA,
        CONCAT(F.UNIDAD_MEDIDA_VENTA," ", F.CANTIDAD_UNIDAD_MEDIDA_VENTA) AS MEDIDA,
        F.PRECIO_UNIDAD_MEDIDA_VENTA AS PRECIO, P.FICHA_TECNICA_ENLACE, TEXTO_COPIAR FROM FRANJA_PRECIOS as F
		LEFT JOIN productos as P
		ON F.CODIGO = P.CODIGO
		WHERE CLASIFICACION = "MALVINAS"
		ORDER BY P.NOMBRE ASC
		;
	END IF;
END $$;
DELIMITER ;
CALL FRANJA_PRECIOS("MALVINAS");

-- DROP TABLE FRANJA_PRECIOS;
SELECT * FROM productos;

SELECT 
    P.NOMBRE,
    MAX(CASE WHEN CONCAT(F.UNIDAD_MEDIDA, ' ', F.CANTIDAD) = 'UNIDAD 1' THEN F.PRECIO END) AS UNIDAD_1,
    MAX(CASE WHEN CONCAT(F.UNIDAD_MEDIDA, ' ', F.CANTIDAD) = 'UNIDAD 5' THEN F.PRECIO END) AS UNIDAD_5,
    MAX(CASE WHEN CONCAT(F.UNIDAD_MEDIDA, ' ', F.CANTIDAD) = 'UNIDAD 10' THEN F.PRECIO END) AS UNIDAD_10
FROM FRANJA_PRECIOS F
INNER JOIN productos P ON F.CODIGO = P.CODIGO
WHERE CLASIFICACION = "MALVINA"
GROUP BY P.NOMBRE
ORDER BY P.NOMBRE ASC;