USE Zeus_Safety_Data_Integration;

-- ============================================
-- PROCEDIMIENTO 1: EXTRACCIÓN GENERAL
-- ============================================

DELIMITER $$

DROP PROCEDURE IF EXISTS extraccion_productos_2026 $$
CREATE PROCEDURE extraccion_productos_2026(IN METHOD VARCHAR(50))
BEGIN
    IF METHOD = 'LISTADO_NORMAL' THEN
        
        SELECT NOMBRE, CODIGO 
        FROM productos 
        WHERE ESTADO = 1 
        ORDER BY NOMBRE;

    ELSEIF METHOD = 'LISTADO_INVENTARIO' THEN

        SELECT ID, NOMBRE, CODIGO, UNIDAD_MEDIDA 
        FROM productos 
        WHERE ESTADO = 1 
        ORDER BY NOMBRE;

    ELSEIF METHOD = "BUSQUEDA_PRODUCTO" THEN
		SELECT ID, NOMBRE, CODIGO 
        FROM productos 
        WHERE ESTADO = 1 
        ORDER BY NOMBRE ASC;
    END IF;
END $$

DELIMITER ;



-- ============================================
-- PROCEDIMIENTO 2: LISTADO GENERAL
-- ============================================

DELIMITER $$

DROP PROCEDURE IF EXISTS listar_productos_general $$
CREATE PROCEDURE listar_productos_general()
BEGIN
    SELECT 
        ID,
        NOMBRE,
        CODIGO,
        UNIDAD_MEDIDA,
        ESTADO
    FROM productos
    ORDER BY NOMBRE;
END $$

DELIMITER ;



-- ============================================
-- PROCEDIMIENTO 3: BUSCAR POR LIKE
-- ============================================

DELIMITER $$

DROP PROCEDURE IF EXISTS listar_producto_nombre_codigo $$
CREATE PROCEDURE listar_producto_nombre_codigo(IN BUSQUEDA VARCHAR(100))
BEGIN
    SELECT 
        NOMBRE,
        CODIGO
    FROM productos
    WHERE ESTADO = 1
      AND (NOMBRE LIKE CONCAT('%', BUSQUEDA, '%')
        OR CODIGO LIKE CONCAT('%', BUSQUEDA, '%'))
    ORDER BY NOMBRE;
END $$

DELIMITER ;



-- ============================================
-- PROCEDIMIENTO 4: CRUD PRODUCTOS
-- ============================================

DELIMITER $$

DROP PROCEDURE IF EXISTS crud_productos $$
CREATE PROCEDURE crud_productos(
    IN P_ID INT,
    IN P_NOMBRE VARCHAR(200),
    IN P_CODIGO VARCHAR(100),
    IN P_UNIDAD_MEDIDA VARCHAR(50),
    IN P_ESTADO TINYINT
)
BEGIN
    IF P_ID = 0 THEN
        
        INSERT INTO productos (NOMBRE, CODIGO, UNIDAD_MEDIDA, ESTADO)
        VALUES (P_NOMBRE, P_CODIGO, P_UNIDAD_MEDIDA, 1);

    ELSE
        
        UPDATE productos
        SET 
            NOMBRE = P_NOMBRE,
            CODIGO = P_CODIGO,
            UNIDAD_MEDIDA = P_UNIDAD_MEDIDA,
            ESTADO = P_ESTADO
        WHERE ID = P_ID;

    END IF;
END $$

DELIMITER ;

SELECT DISTINCT UNIDAD_MEDIDA FROM productos;

-- Nuevo paso (corrigiendo)
CREATE TABLE productos_backup AS SELECT * FROM productos;

ALTER TABLE productos
ADD COLUMN unidad_new VARCHAR(50) NULL;

UPDATE productos
SET unidad_new = UNIDAD_MEDIDA;

UPDATE productos
SET unidad_new = TRIM(UPPER(unidad_new))
WHERE unidad_new IS NOT NULL;

UPDATE productos
SET unidad_new = CASE
    WHEN unidad_new IN ('KG','KILO','KILOS','KILOGRAMO','KILOGRAMOS') THEN 'KG'
    WHEN unidad_new IN ('UNIDAD','UNI','UND','UN') THEN 'UNIDAD'
    ELSE 'UNIDAD'
END;

SELECT DISTINCT unidad_new FROM productos;

ALTER TABLE productos DROP COLUMN UNIDAD_MEDIDA;

ALTER TABLE productos 
CHANGE unidad_new UNIDAD_MEDIDA VARCHAR(50) NULL;

ALTER TABLE productos 
MODIFY UNIDAD_MEDIDA ENUM('UNIDAD', 'KG') NOT NULL;

DELIMITER $$
DROP PROCEDURE IF EXISTS listar_productos_general $$
CREATE PROCEDURE listar_productos_general()
BEGIN
    SELECT ID, NOMBRE, CODIGO, UNIDAD_MEDIDA, ESTADO
    FROM productos
    ORDER BY NOMBRE;
END $$
DELIMITER ;

DELIMITER $$
DROP PROCEDURE IF EXISTS listar_producto_nombre_codigo $$
CREATE PROCEDURE listar_producto_nombre_codigo(IN BUSQUEDA VARCHAR(100))
BEGIN
    SELECT NOMBRE, CODIGO
    FROM productos
    WHERE ESTADO = 1
      AND (NOMBRE LIKE CONCAT('%', BUSQUEDA, '%')
        OR CODIGO LIKE CONCAT('%', BUSQUEDA, '%'))
    ORDER BY NOMBRE;
END $$
DELIMITER ;

DELIMITER $$
DROP PROCEDURE IF EXISTS crud_productos $$
CREATE PROCEDURE crud_productos(
    IN P_ID INT,
    IN P_NOMBRE VARCHAR(200),
    IN P_CODIGO VARCHAR(100),
    IN P_UNIDAD_MEDIDA VARCHAR(50),
    IN P_ESTADO TINYINT
)
BEGIN
    IF P_ID = 0 THEN
        INSERT INTO productos (NOMBRE, CODIGO, UNIDAD_MEDIDA, ESTADO)
        VALUES (P_NOMBRE, P_CODIGO, P_UNIDAD_MEDIDA, 1);
    ELSE
        UPDATE productos
        SET NOMBRE = P_NOMBRE,
            CODIGO = P_CODIGO,
            UNIDAD_MEDIDA = P_UNIDAD_MEDIDA,
            ESTADO = P_ESTADO
        WHERE ID = P_ID;
    END IF;
END $$
DELIMITER ;

CALL crud_productos(0, 'Producto Test', 'PRD999', 'KG', 1);

CALL crud_productos(5, 'Producto Modificado', 'PRD555', 'UNIDAD', 1);

SHOW CREATE TABLE productos;


-- ============================================
-- PROCEDIMIENTO 5: LISTADO NUEVO
-- ============================================

DROP PROCEDURE IF EXISTS listar_productos_general;

DELIMITER $$
CREATE PROCEDURE listar_productos_general()
BEGIN
    SELECT 
        ID,
        CODIGO,
        NOMBRE,
        CATEGORIA,
        TIPO_PRODUCTO,
        COLOR_TIPO,
        TAMAÑO,
        PARES_POR_CAJA,
        FICHA_TECNICA_ENLACE,
        IMG_URL
    FROM productos
    WHERE ESTADO = 1
    ORDER BY NOMBRE;
END$$
DELIMITER ;



#######################################
-- FRANJA DE PRECIOS
#######################################
DROP PROCEDURE IF EXISTS FRANJA_PRECIOS;
DELIMITER $$;
CREATE PROCEDURE FRANJA_PRECIOS(IN METHOD VARCHAR(30), IN IN_CLASIFICACION VARCHAR(30))
BEGIN
	-- variables declaradas
    DECLARE R_CODIGO VARCHAR(30);
    DECLARE R_CLASIFICACION VARCHAR(30);
	IF METHOD = "LISTADO_FRANJA_PRECIOS" THEN
        SELECT F.ID, F.CODIGO, P.NOMBRE,
        CONCAT(UNIDAD_MEDIDA_CAJA," ",CANTIDAD_CAJA) AS CANTIDAD_CAJA,
        CONCAT(F.UNIDAD_MEDIDA_VENTA," ", F.CANTIDAD_UNIDAD_MEDIDA_VENTA) AS MEDIDA,
        F.PRECIO_UNIDAD_MEDIDA_VENTA AS PRECIO, P.FICHA_TECNICA_ENLACE, TEXTO_COPIAR FROM FRANJA_PRECIOS as F
		LEFT JOIN productos as P
		ON F.CODIGO = P.CODIGO
		WHERE CLASIFICACION = IN_CLASIFICACION
		ORDER BY P.NOMBRE ASC;
	ELSEIF METHOD = "CONFIGURACION_FRANJA_PRECIOS" THEN
		SELECT F.ID, F.CODIGO, P.NOMBRE,
        CONCAT(UNIDAD_MEDIDA_CAJA," ",CANTIDAD_CAJA) AS CANTIDAD_CAJA,
        CONCAT(F.UNIDAD_MEDIDA_VENTA," ", F.CANTIDAD_UNIDAD_MEDIDA_VENTA) AS MEDIDA,
        F.PRECIO_UNIDAD_MEDIDA_VENTA AS PRECIO, TEXTO_COPIAR FROM FRANJA_PRECIOS as F
		LEFT JOIN productos as P
		ON F.CODIGO = P.CODIGO
		WHERE CLASIFICACION = IN_CLASIFICACION
		ORDER BY P.NOMBRE ASC;
    ELSEIF METHOD = "OBTENER_PRECIO_PRODUCTO" THEN
		SET R_CODIGO = SUBSTRING_INDEX(IN_CLASIFICACION, '/', 1);
        SET R_CLASIFICACION = SUBSTRING_INDEX(SUBSTRING_INDEX(IN_CLASIFICACION, '/', 2), '/', -1);
        
        SELECT CODIGO, CONCAT(CANTIDAD_UNIDAD_MEDIDA_VENTA, " ", UNIDAD_MEDIDA_VENTA) AS MEDIDA,
        PRECIO_UNIDAD_MEDIDA_VENTA FROM FRANJA_PRECIOS
        WHERE CODIGO = R_CODIGO
        AND CLASIFICACION = R_CLASIFICACION
        ;
    END IF;
END $$;
DELIMITER ;
CALL FRANJA_PRECIOS("LISTADO_FRANJA_PRECIOS","MALVINAS");
CALL FRANJA_PRECIOS("CONFIGURACION_FRANJA_PRECIOS","MALVINAS");
CALL FRANJA_PRECIOS("OBTENER_PRECIO_PRODUCTO","GZ-L202-8/MALVINAS");

-- DROP TABLE FRANJA_PRECIOS;
SELECT * FROM productos;
select DISTINCT(CLASIFICACION) from FRANJA_PRECIOS;

DROP PROCEDURE IF EXISTS PRODUCTOS_PAGINA_ESTATICA;
DELIMITER $$;
CREATE PROCEDURE PRODUCTOS_PAGINA_ESTATICA(IN METHOD VARCHAR(30))
BEGIN
	IF METHOD = "LISTADO_PRODUCTOS_ESTATICA" THEN
        SELECT ID, NOMBRE, CATEGORIA, TIPO_PRODUCTO, COLOR_TIPO, PARES_POR_CAJA, 
        FICHA_TECNICA_ENLACE, IMG_URL,
        DESCRIPCION,
        "1" AS PRECIO
		FROM productos
		WHERE ESTADO = 1 AND ID != 20
        ORDER BY NOMBRE ASC
        ;
    ELSEIF METHOD = "CONFIGURACION_PRODUCTOS" THEN
		SELECT DISTINCT CATEGORIA FROM productos;
    ELSEIF METHOD = "PRODUCTOS_ESTRELLA" THEN
		WITH PRODUCTOS_ESTRELLA AS(
		select CODIGO, PRODUCTO, SUM(TOTAL) AS TOTAL from detalle_venta
		GROUP BY CODIGO, PRODUCTO
		ORDER BY SUM(TOTAL) DESC
		limit 20
		)
        SELECT PID, P.NOMBRE, P.CATEGORIA, P.TIPO_PRODUCTO, P.COLOR_TIPO, P.PARES_POR_CAJA, 
        P.FICHA_TECNICA_ENLACE, P.IMG_URL,
        DESCRIPCION,
        "1" AS PRECIO
		FROM productos AS P
        INNER JOIN PRODUCTOS_ESTRELLA AS E
        ON P.CODIGO = E.CODIGO
		WHERE ESTADO = 1
        ORDER BY NOMBRE ASC;
    END IF;
END $$;
DELIMITER ;
CALL PRODUCTOS_PAGINA_ESTATICA("LISTADO_PRODUCTOS_ESTATICA");

SELECT F.ID, F.CODIGO, P.NOMBRE,
        CONCAT(UNIDAD_MEDIDA_CAJA," ",CANTIDAD_CAJA) AS CANTIDAD_CAJA,
        CONCAT(F.UNIDAD_MEDIDA_VENTA," ", F.CANTIDAD_UNIDAD_MEDIDA_VENTA) AS MEDIDA,
        F.PRECIO_UNIDAD_MEDIDA_VENTA AS PRECIO, P.FICHA_TECNICA_ENLACE, TEXTO_COPIAR FROM FRANJA_PRECIOS as F
		LEFT JOIN productos as P
		ON F.CODIGO = P.CODIGO
		WHERE CLASIFICACION = "MALVINAS"
		AND NOMBRE LIKE "%Guantes Econoflex Rojo 7%"
		ORDER BY P.NOMBRE ASC;
        
DELETE FROM FRANJA_PRECIOS WHERE ID = 854;


################################################################################################################
SELECT F.ID, F.CODIGO, P.NOMBRE,
        CONCAT(UNIDAD_MEDIDA_CAJA," ",CANTIDAD_CAJA) AS CANTIDAD_CAJA,
        CONCAT(F.UNIDAD_MEDIDA_VENTA," ", F.CANTIDAD_UNIDAD_MEDIDA_VENTA) AS MEDIDA,
        F.PRECIO_UNIDAD_MEDIDA_VENTA AS PRECIO, P.FICHA_TECNICA_ENLACE, TEXTO_COPIAR FROM FRANJA_PRECIOS as F
		LEFT JOIN productos as P
		ON F.CODIGO = P.CODIGO
		WHERE CLASIFICACION = IN_CLASIFICACION
		ORDER BY P.NOMBRE ASC;
################################################################################################################
SELECT F.ID, F.CODIGO, P.NOMBRE,
        CONCAT(UNIDAD_MEDIDA_CAJA," ",CANTIDAD_CAJA) AS CANTIDAD_CAJA,
        CONCAT(F.UNIDAD_MEDIDA_VENTA," ", F.CANTIDAD_UNIDAD_MEDIDA_VENTA) AS MEDIDA,
        F.PRECIO_UNIDAD_MEDIDA_VENTA AS PRECIO, P.FICHA_TECNICA_ENLACE FROM FRANJA_PRECIOS as F
		LEFT JOIN productos as P
		ON F.CODIGO = P.CODIGO
		WHERE CLASIFICACION = IN_CLASIFICACION
		ORDER BY P.NOMBRE ASC;
        
select * from productos WHERE IMG_URL IS NOT NULL order by nombre;