SELECT * FROM colaboradores limit 20;
 -- #####################################################
 -- ###### ACTUALIZACIÓN DE TABLAS
 -- #####################################################
ALTER TABLE colaboradores
ADD COLUMN HIJOS_BOOLEAN BOOLEAN;
ALTER TABLE colaboradores
ADD COLUMN TIPO_DOCUMENTO ENUM('DNI','PASAPORTE') NOT NULL;
ALTER TABLE colaboradores
ADD COLUMN NUMERO_DOCUMENTO INT NOT NULL;
ALTER TABLE colaboradores
ADD COLUMN CANT_HIJOS INT;
ALTER TABLE colaboradores
ADD COLUMN ESTADO_CIVIL ENUM('SOLTERO','CASADO','SOLETRA','CASADA');
ALTER TABLE colaboradores
ADD COLUMN DIRECCION TEXT;
ALTER TABLE colaboradores
ADD COLUMN GOOGLE_MAPS TEXT;
ALTER TABLE colaboradores
ADD COLUMN OCUPACION VARCHAR(50);
ALTER TABLE colaboradores
ADD COLUMN CARGO VARCHAR(50);
ALTER TABLE colaboradores
ADD COLUMN SEGURO_VIDA_LEY BOOLEAN;
ALTER TABLE colaboradores
ADD COLUMN SEGURO_FECHA_INICIO DATE;
ALTER TABLE colaboradores
ADD COLUMN SEGURO_FECHA_VENCIMIENTO DATE;

-- TABLAS PARA CORREOS Y NUMEROS
CREATE TABLE IF NOT EXISTS MEDIOS_COMUNICACION(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_COLABORADOR INT REFERENCES colaboradores(ID_PERSONA),
NOMBRE VARCHAR(50) NOT NULL,
MEDIO ENUM('TELEFONO','CORREO','TELEFONO_EMERGENCIA') NOT NULL,
TIPO ENUM('CORPORATIVO','PERSONAL') NOT NULL,
CONTENIDO VARCHAR(50),
ESTADO BOOLEAN DEFAULT TRUE
);

CREATE TABLE IMAGENES_COLABORADOR(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_COLABORADOR INT REFERENCES colaboradores(ID_PERSONA),
NOMBRE VARCHAR(50),
TIPO VARCHAR(30),
IMAGE_URL TEXT,
ESTADO CHAR(1) DEFAULT 1
);
INSERT INTO IMAGENES_COLABORADOR(ID_COLABORADOR, NOMBRE, TIPO, IMAGE_URL) 
VALUES (15,"Foto de Perfil", "FOTOCHECK","");

INSERT INTO MEDIOS_COMUNICACION(ID_COLABORADOR, NOMBRE, MEDIO, TIPO, CONTENIDO)
VALUES (15,"TELEFONO VENTAS 1", "TELEFONO","CORPORATIVO","935447178");

SELECT C.NOMBRE, JSON_ARRAYAGG(JSON_OBJECT('NOMBRE',M.NOMBRE,'MEDIO',M.MEDIO, 'TIPO', M.TIPO,'CONTENIDO', M.CONTENIDO)) AS DATOS
FROM colaboradores as C
INNER JOIN MEDIOS_COMUNICACION AS M
ON C.ID_PERSONA = ID_COLABORADOR
WHERE C.ESTADO = 1
GROUP BY C.NOMBRE
LIMIT 10;