SELECT * FROM colaboradores limit 20;
 -- #####################################################
 -- ###### ACTUALIZACIÓN DE TABLAS
 -- #####################################################
ALTER TABLE colaboradores
ADD COLUMN HIJOS_BOOLEAN BOOLEAN;
ALTER TABLE colaboradores
ADD COLUMN TIPO_DOCUMENTO ENUM('DNI','PASAPORTE') NOT NULL;
ALTER TABLE colaboradores
ADD COLUMN NUMERO_DOCUMENTO INT NOT NULL;
ALTER TABLE colaboradores
ADD COLUMN CANT_HIJOS INT;
ALTER TABLE colaboradores
ADD COLUMN ESTADO_CIVIL ENUM('SOLTERO','CASADO','SOLETRA','CASADA');
ALTER TABLE colaboradores
ADD COLUMN DIRECCION TEXT;
ALTER TABLE colaboradores
ADD COLUMN GOOGLE_MAPS TEXT;
ALTER TABLE colaboradores
ADD COLUMN OCUPACION VARCHAR(50);
ALTER TABLE colaboradores
ADD COLUMN CARGO VARCHAR(50);
ALTER TABLE colaboradores
ADD COLUMN SEGURO_VIDA_LEY BOOLEAN;
ALTER TABLE colaboradores
ADD COLUMN SEGURO_FECHA_INICIO DATE;
ALTER TABLE colaboradores
ADD COLUMN SEGURO_FECHA_VENCIMIENTO DATE;

-- TABLAS PARA CORREOS Y NUMEROS
CREATE TABLE IF NOT EXISTS MEDIOS_COMUNICACION(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_COLABORADOR INT REFERENCES colaboradores(ID_PERSONA),
NOMBRE VARCHAR(50) NOT NULL,
MEDIO ENUM('TELEFONO','CORREO','TELEFONO_EMERGENCIA') NOT NULL,
TIPO ENUM('CORPORATIVO','PERSONAL') NOT NULL,
CONTENIDO VARCHAR(50),
ESTADO BOOLEAN DEFAULT TRUE
);

CREATE TABLE IMAGENES_COLABORADOR(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_COLABORADOR INT REFERENCES colaboradores(ID_PERSONA),
NOMBRE VARCHAR(50),
TIPO VARCHAR(30),
IMAGE_URL TEXT,
ESTADO CHAR(1) DEFAULT 1
);
INSERT INTO IMAGENES_COLABORADOR(ID_COLABORADOR, NOMBRE, TIPO, IMAGE_URL) 
VALUES (15,"Foto de Perfil", "FOTOCHECK","");

INSERT INTO MEDIOS_COMUNICACION(ID_COLABORADOR, NOMBRE, MEDIO, TIPO, CONTENIDO)
VALUES (15,"TELEFONO VENTAS 1", "TELEFONO","CORPORATIVO","935447178");

SELECT C.NOMBRE, JSON_ARRAYAGG(JSON_OBJECT('NOMBRE',M.NOMBRE,'MEDIO',M.MEDIO, 'TIPO', M.TIPO,'CONTENIDO', M.CONTENIDO)) AS DATOS
FROM colaboradores as C
INNER JOIN MEDIOS_COMUNICACION AS M
ON C.ID_PERSONA = ID_COLABORADOR
WHERE C.ESTADO = 1
GROUP BY C.NOMBRE
LIMIT 10;

INNER JOIN MEDIOS_COMUNICACION AS M
OC.ID_PERSONA = ID_COLABORADOR
WHERE C.ESTADO = 1
GROUP BY C.NOMBRE
LIMIT 10;
<<<<<<< Updated upstream
LIMIT 10;
=======
LIMIT 10;

SHOW PROCEDURE STATUS;

-- 1. PROCEDIMIENTO: Obtener medios de comunicación de un colaborador
DELIMITER //
CREATE PROCEDURE IF NOT EXISTS sp_obtener_medios_comunicacion(
    IN p_id_persona INT
)
BEGIN
    SELECT 
        ID,
        ID_COLABORADOR,
        NOMBRE,
        MEDIO,
        TIPO,
        CONTENIDO,
        ESTADO
    FROM MEDIOS_COMUNICACION
    WHERE ID_COLABORADOR = p_id_persona
      AND ESTADO = TRUE
    ORDER BY MEDIO, ID;
END //
DELIMITER ;

-- 2. PROCEDIMIENTO: Actualizar medios de comunicación
DELIMITER //
CREATE PROCEDURE IF NOT EXISTS sp_actualizar_medios_comunicacion(
    IN p_id_persona INT,
    IN p_medios JSON
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;
    
    START TRANSACTION;
    
    -- Desactivar todos los medios existentes del colaborador
    UPDATE MEDIOS_COMUNICACION
    SET ESTADO = FALSE
    WHERE ID_COLABORADOR = p_id_persona;
    
    -- Insertar los nuevos medios
    INSERT INTO MEDIOS_COMUNICACION (
        ID_COLABORADOR,
        NOMBRE,
        MEDIO,
        TIPO,
        CONTENIDO,
        ESTADO
    )
    SELECT 
        p_id_persona,
        NULLIF(JSON_UNQUOTE(JSON_EXTRACT(medio_item.value, '$.NOMBRE')), '') AS NOMBRE,
        JSON_UNQUOTE(JSON_EXTRACT(medio_item.value, '$.MEDIO')) AS MEDIO,
        JSON_UNQUOTE(JSON_EXTRACT(medio_item.value, '$.TIPO')) AS TIPO,
        JSON_UNQUOTE(JSON_EXTRACT(medio_item.value, '$.CONTENIDO')) AS CONTENIDO,
        TRUE AS ESTADO
    FROM JSON_TABLE(
        p_medios,
        '$[*]' COLUMNS (
            value JSON PATH '$'
        )
    ) AS medio_item;
    
    COMMIT;
END //
DELIMITER ;

-- 3. VERIFICAR QUE SE CREARON CORRECTAMENTE
SHOW PROCEDURE STATUS WHERE Db = DATABASE() AND Name LIKE 'sp_%medios%';
>>>>>>> Stashed changes
