########################################
-- PROCEDIMIENTO COLABORADORES
########################################
-- Listado de procedimientos
DROP PROCEDURE IF EXISTS COLABORADORES_DATOS;
DELIMITER $$
CREATE PROCEDURE COLABORADORES_DATOS(in method varchar(50), in userr varchar(50))
BEGIN
	IF method = "LISTADO_NOTIFICACIONES" THEN
		SELECT N.ID, C.NOMBRE, TITULO, CUERPO, TIPO, URL_ACCION, ESTADO_LECTURA FROM NOTIFICACIONES AS N
		INNER JOIN colaboradores AS C
		ON C.ID_PERSONA = N.ID_COLABORADOR
		WHERE N.ESTADO = "1" and C.USUARIO=userr
        ORDER BY N.FECHA_CREACION DESC
        LIMIT 15;
    ELSEIF method = "LISTADO_COLABORADORES" THEN
		SELECT ID_PERSONA,NOMBRE, APELLIDO, AREA, CORREO, FECHA_NACIMIENTO
		FROM colaboradores WHERE CULMINACION = "ACTUALMENTE" AND ESTADO=1 ORDER BY ID_PERSONA ASC;
	elseif method = "COLABORADORES_INACTIVOS" THEN
		SELECT ID_PERSONA,NOMBRE, APELLIDO, AREA, CORREO, FECHA_NACIMIENTO
		FROM colaboradores WHERE CULMINACION = "ACTUALMENTE" AND ESTADO=0 ORDER BY ID_PERSONA ASC;
    ELSEIF method = "COLABORADORES" THEN
		SELECT ID_PERSONA,NOMBRE,AREA
		FROM colaboradores WHERE CULMINACION = "ACTUALMENTE" AND ESTADO=1 ORDER BY ID_PERSONA ASC;
    ELSEIF method = "NOTIFICACION_LEIDA" THEN
		SET time_zone = 'America/Lima';
		UPDATE NOTIFICACIONES SET ESTADO_LECTURA = 1, FECHA_LECTURA= now() WHERE ID = userr; -- user no es usuario, es el id entrante de la notificacion
    END IF;
END $$;
DELIMITER ;

CALL COLABORADORES_DATOS('LISTADO_NOTIFICACIONES','hervinzeus');
CALL COLABORADORES_DATOS('NOTIFICACION_LEIDA',1);
UPDATE NOTIFICACIONES SET ESTADO_LECTURA = 0 WHERE ID = 1;
UPDATE NOTIFICACIONES SET ESTADO_LECTURA = 0 WHERE ID = 3;

SET @ID= 1;

########################################
########################################
-- PROCEDIMIENTO COLABORADORES - REMASTERIZADO
########################################
########################################
DROP PROCEDURE IF EXISTS COLABORADORES2026;
DELIMITER $$
CREATE PROCEDURE COLABORADORES2026(in method varchar(50), in userr varchar(50))
BEGIN
    IF method = "LISTADO_COLABORADORES" THEN
		SELECT ID_PERSONA,NOMBRE, APELLIDO, AREA, CORREO, FECHA_NACIMIENTO
		FROM colaboradores WHERE CULMINACION = "ACTUALMENTE" AND ESTADO=1 ORDER BY ID_PERSONA ASC;
	ELSEIF method = "COLABORADORES_INACTIVOS" THEN
		SELECT ID_PERSONA,NOMBRE, APELLIDO, AREA, CORREO, FECHA_NACIMIENTO
		FROM colaboradores WHERE CULMINACION = "ACTUALMENTE" AND ESTADO=0 ORDER BY ID_PERSONA ASC;
    ELSEIF method = "COLABORADORES" THEN
		SELECT ID_PERSONA,NOMBRE,AREA
		FROM colaboradores WHERE CULMINACION = "ACTUALMENTE" AND ESTADO=1 ORDER BY ID_PERSONA ASC;
	ELSEIF method = "PERFIL_COLABORADOR" THEN
		SELECT C.NOMBRE, SEGUNDO_NOMBRE, APELLIDO, SEGUNDO_APELLIDO
		FECHA_NACIMIENTO, FECHA_INGRESO, FECHA_PLANILLA, USUARIO, CONTRASEÑA2, CORREO,
		A.NOMBRE, R.NOMBRE
		FROM colaboradores as C
		INNER JOIN AREAS AS A
		ON C.AREA_PRINCIPAL = A.ID
		INNER JOIN ROL AS R
		ON R.ID = C.ID_ROL
		WHERE USUARIO = userr;
	END IF;
END $$;
DELIMITER ;


DROP PROCEDURE IF EXISTS NOTIFICACIONES2026;
DELIMITER $$
CREATE PROCEDURE NOTIFICACIONES2026(in method varchar(50), in userr varchar(50))
BEGIN
	IF method = "LISTADO_NOTIFICACIONES" THEN
		SELECT N.ID, C.NOMBRE, TITULO, CUERPO, TIPO, URL_ACCION, ESTADO_LECTURA FROM NOTIFICACIONES AS N
		INNER JOIN colaboradores AS C
		ON C.ID_PERSONA = N.ID_COLABORADOR
		WHERE N.ESTADO = "1" and C.USUARIO=userr
        ORDER BY N.FECHA_CREACION DESC
        LIMIT 15;
    ELSEIF method = "NOTIFICACION_LEIDA" THEN
		SET time_zone = 'America/Lima';
		UPDATE NOTIFICACIONES SET ESTADO_LECTURA = 1, FECHA_LECTURA= now() WHERE ID = userr; -- user no es usuario, es el id entrante de la notificacion
    END IF;
END $$;
DELIMITER ;