USE Zeus_Safety_Data_Integration;
########################################
-- PROCEDIMIENTO COLABORADORES
########################################
-- Listado de procedimientos
DROP PROCEDURE IF EXISTS COLABORADORES_DATOS;
DELIMITER $$
CREATE PROCEDURE COLABORADORES_DATOS(in method varchar(50), in userr varchar(50))
BEGIN
	IF method = "LISTADO_NOTIFICACIONES" THEN
		SELECT N.ID, C.NOMBRE, TITULO, CUERPO, TIPO, URL_ACCION, ESTADO_LECTURA FROM NOTIFICACIONES AS N
		INNER JOIN colaboradores AS C
		ON C.ID_PERSONA = N.ID_COLABORADOR
		WHERE N.ESTADO = "1" and C.USUARIO=userr
        ORDER BY N.FECHA_CREACION DESC
        LIMIT 15;
    ELSEIF method = "LISTADO_COLABORADORES" THEN
		SELECT ID_PERSONA,NOMBRE, APELLIDO, AREA, CORREO, FECHA_NACIMIENTO
		FROM colaboradores WHERE CULMINACION = "ACTUALMENTE" AND ESTADO=1 ORDER BY ID_PERSONA ASC;
	elseif method = "COLABORADORES_INACTIVOS" THEN
		SELECT ID_PERSONA,NOMBRE, APELLIDO, AREA, CORREO, FECHA_NACIMIENTO
		FROM colaboradores WHERE CULMINACION = "ACTUALMENTE" AND ESTADO=0 ORDER BY ID_PERSONA ASC;
    ELSEIF method = "COLABORADORES" THEN
		SELECT ID_PERSONA,NOMBRE,AREA
		FROM colaboradores WHERE CULMINACION = "ACTUALMENTE" AND ESTADO=1 ORDER BY ID_PERSONA ASC;
    ELSEIF method = "NOTIFICACION_LEIDA" THEN
		SET time_zone = 'America/Lima';
		UPDATE NOTIFICACIONES SET ESTADO_LECTURA = 1, FECHA_LECTURA= now() WHERE ID = userr; -- user no es usuario, es el id entrante de la notificacion
    END IF;
END $$;
DELIMITER ;

CALL COLABORADORES_DATOS('LISTADO_NOTIFICACIONES','hervinzeus');
CALL COLABORADORES_DATOS('NOTIFICACION_LEIDA',1);
UPDATE NOTIFICACIONES SET ESTADO_LECTURA = 0 WHERE ID = 1;
UPDATE NOTIFICACIONES SET ESTADO_LECTURA = 0 WHERE ID = 3;

SET @ID= 1;

########################################
########################################
-- PROCEDIMIENTO COLABORADORES - REMASTERIZADO
########################################
########################################
DROP PROCEDURE IF EXISTS COLABORADORES2026;
DELIMITER $$
CREATE PROCEDURE COLABORADORES2026(in method varchar(50), in userr varchar(50))
BEGIN
    IF method = "LISTADO_COLABORADORES_ACTIVOS_PERMISOS" THEN
		SELECT ID_PERSONA,NOMBRE, APELLIDO, AREA, CORREO, FECHA_NACIMIENTO
		FROM colaboradores WHERE CULMINACION = "ACTUALMENTE" AND ESTADO=1 ORDER BY ID_PERSONA ASC;
	ELSEIF method = "LISTADO_COLABORADORES_INACTIVOS_PERMISOS" THEN
		SELECT ID_PERSONA,NOMBRE, APELLIDO, AREA, CORREO, FECHA_NACIMIENTO
		FROM colaboradores WHERE CULMINACION = "ACTUALMENTE" AND ESTADO=0 ORDER BY ID_PERSONA ASC;
    ELSEIF method = "COLABORADORES" THEN
		SELECT ID_PERSONA,NOMBRE,AREA
		FROM colaboradores WHERE CULMINACION = "ACTUALMENTE" AND ESTADO=1 ORDER BY ID_PERSONA ASC;
	ELSEIF method = "PERFIL_COLABORADOR" THEN
		SELECT ID_PERSONA, C.NOMBRE, SEGUNDO_NOMBRE, APELLIDO, SEGUNDO_APELLIDO,
		FECHA_NACIMIENTO, FECHA_INGRESO, FECHA_PLANILLA, USUARIO, CONTRASEÑA2, CORREO,
		A.NOMBRE, R.NOMBRE AS AREA, I.IMAGE_URL
		FROM colaboradores as C
		INNER JOIN AREAS AS A
		ON C.AREA_PRINCIPAL = A.ID
		INNER JOIN ROL AS R
		ON R.ID = C.ID_ROL
		LEFT JOIN IMAGENES_COLABORADOR AS I
		ON I.ID_COLABORADOR = C.ID_PERSONA
		WHERE I.ESTADO=1 AND TIPO = "FOTOCHECK"
		AND USUARIO = userr;
	ELSEIF method = "LISTADO_COLABORADORES_RECURSOS_HUMANOS" THEN
		SELECT * FROM DATOS_CLIENTES_RECURSOS_HUMANOS AS D;
    ELSEIF method = "FECHA_NACIMIENTOS_CALENDARIO" THEN
		SELECT ID_PERSONA, FECHA_NACIMIENTO, C.NOMBRE AS NOMBRE, APELLIDO, A.NOMBRE AS AREA
        FROM colaboradores as C
        INNER JOIN AREAS AS A
		ON C.AREA_PRINCIPAL = A.ID
        WHERE C.ESTADO = 1
        AND CULMINACION = "ACTUALMENTE"
        ORDER BY MONTH(FECHA_NACIMIENTO) ASC;
    END IF;
END $$;
DELIMITER ;
CALL COLABORADORES2026("PERFIL_COLABORADOR", "random");
CALL COLABORADORES2026("FECHA_NACIMIENTOS_CALENDARIO", "random");

DROP PROCEDURE IF EXISTS NOTIFICACIONES2026;
DELIMITER $$
CREATE PROCEDURE NOTIFICACIONES2026(in method varchar(50), in userr varchar(50))
BEGIN
	IF method = "LISTADO_NOTIFICACIONES" THEN
		SELECT N.ID, C.NOMBRE, TITULO, CUERPO, TIPO, URL_ACCION, ESTADO_LECTURA FROM NOTIFICACIONES AS N
		INNER JOIN colaboradores AS C
		ON C.ID_PERSONA = N.ID_COLABORADOR
		WHERE N.ESTADO = "1" and C.USUARIO=userr
        ORDER BY N.FECHA_CREACION DESC
        LIMIT 15;
    ELSEIF method = "NOTIFICACION_LEIDA" THEN
		SET time_zone = 'America/Lima';
		UPDATE NOTIFICACIONES SET ESTADO_LECTURA = 1, FECHA_LECTURA= now() WHERE ID = userr; -- user no es usuario, es el id entrante de la notificacion
    END IF;
END $$;
DELIMITER ;

DROP PROCEDURE IF EXISTS INSERTAR_ACTUALIZAR_COLABORADOR;
DELIMITER $$;
CREATE PROCEDURE INSERTAR_ACTUALIZAR_COLABORADOR(IN METHOD VARCHAR(30), IN DATOS JSON)
BEGIN
	IF METHOD = "INSERTAR_COLABORADOR" THEN
		INSERT INTO colaboradores(NOMBRE,APELLIDO,AREA,TIPO_DOCUMENTO,NUMERO_DOCUMENTO)
        VALUES(
			(SELECT DATOS ->> '$.NOMBRE'),
            (SELECT DATOS ->> '$.APELLIDO'),
            (SELECT DATOS ->> '$.AREA'),
            (SELECT DATOS ->> '$.TIPO_DOCUMENTO'),
            (SELECT DATOS ->> '$.NUMERO_DOCUMENTO')
        );
	ELSEIF METHOD = "ACTUALIZAR_DATOS_MEDIOS_COMUNICACION" THEN
		UPDATE MEDIOS_COMUNICACION SET NOMBRE=""
        WHERE ID_PERSONA = (SELECT DATOS ->> '$.ID_PERSONA');
	ELSEIF METHOD = "INSERTAR_DATOS_MEDIOS_COMUNICACION" THEN
		-- MEDIO ('TELEFONO','CORREO','TELEFONO_EMERGENCIA')
		-- TIPO ('CORPORATIVO','PERSONAL')
		INSERT INTO MEDIOS_COMUNICACION(ID_COLABORADOR, NOMBRE, MEDIO, TIPO, CONTENIDO)
		VALUES ('$.ID_COLABORADOR','$.NOMBRE','$.MEDIO','$.TIPO','$.CONTENIDO');
	ELSEIF METHOD = "ELIMINAR_DATOS_MEDIOS_COMUNICACION" THEN
		DELETE FROM MEDIOS_COMUNICACION WHERE ID = (SELECT DATOS ->> '$.ID');
	END IF;
END $$;
DELIMITER ;
CALL INSERTAR_ACTUALIZAR_COLABORADOR();

show procedure status;
CALL sp_listado_solicitudes_respuestas_administracion();