DROP VIEW IF EXISTS DATOS_CLIENTES_RECURSOS_HUMANOS;
CREATE VIEW DATOS_CLIENTES_RECURSOS_HUMANOS AS
SELECT C.ID_PERSONA,C.NOMBRE, C.SEGUNDO_NOMBRE, C.APELLIDO, C.SEGUNDO_APELLIDO, FECHA_NACIMIENTO, C.TIPO_DOCUMENTO, C.NUMERO_DOCUMENTO,
HIJOS_BOOLEAN,CANT_HIJOS,ESTADO_CIVIL,
DIRECCION,GOOGLE_MAPS,
OCUPACION, CARGO,
SEGURO_VIDA_LEY,
SEGURO_FECHA_INICIO,
SEGURO_FECHA_VENCIMIENTO,
JSON_ARRAYAGG(JSON_OBJECT('NOMBRE',M.NOMBRE,'MEDIO',M.MEDIO, 'TIPO', M.TIPO,'CONTENIDO', M.CONTENIDO)) AS DATOS
FROM colaboradores as C
LEFT JOIN MEDIOS_COMUNICACION AS M
ON C.ID_PERSONA = ID_COLABORADOR
WHERE C.ESTADO = 1
GROUP BY
C.ID_PERSONA, C.NOMBRE, C.SEGUNDO_NOMBRE, C.APELLIDO, C.SEGUNDO_APELLIDO, FECHA_NACIMIENTO, C.TIPO_DOCUMENTO, C.NUMERO_DOCUMENTO,
HIJOS_BOOLEAN,CANT_HIJOS,ESTADO_CIVIL,
DIRECCION,GOOGLE_MAPS,
OCUPACION, CARGO,
SEGURO_VIDA_LEY,
SEGURO_FECHA_INICIO,
SEGURO_FECHA_VENCIMIENTO
ORDER BY C.ID_PERSONA ASC
LIMIT 10;