DROP VIEW IF EXISTS DATOS_CLIENTES_RECURSOS_HUMANOS;
CREATE VIEW DATOS_CLIENTES_RECURSOS_HUMANOS AS
	SELECT C.ID_PERSONA,C.ESTADO,C.NOMBRE, C.SEGUNDO_NOMBRE, C.APELLIDO, C.SEGUNDO_APELLIDO, FECHA_NACIMIENTO, C.TIPO_DOCUMENTO, C.NUMERO_DOCUMENTO,
	HIJOS_BOOLEAN,CANT_HIJOS,ESTADO_CIVIL,
	DIRECCION,GOOGLE_MAPS,
	OCUPACION, CARGO, R.NOMBRE AS ROL, A.NOMBRE AS AREA,
	SEGURO_VIDA_LEY,
	SEGURO_FECHA_INICIO,
	SEGURO_FECHA_VENCIMIENTO,
	JSON_ARRAYAGG(JSON_OBJECT('NOMBRE',M.NOMBRE,'MEDIO',M.MEDIO, 'TIPO', M.TIPO,'CONTENIDO', M.CONTENIDO)) AS DATOS
FROM colaboradores as C
LEFT JOIN AREAS AS A
ON A.ID = C.AREA_PRINCIPAL
LEFT JOIN ROL AS R
ON R.ID = C.ID_ROL
LEFT JOIN MEDIOS_COMUNICACION AS M
ON C.ID_PERSONA = ID_COLABORADOR
WHERE C.ESTADO IN (0,1)
GROUP BY
	C.ID_PERSONA, C.ESTADO,C.NOMBRE, C.SEGUNDO_NOMBRE, C.APELLIDO, C.SEGUNDO_APELLIDO, FECHA_NACIMIENTO, C.TIPO_DOCUMENTO, C.NUMERO_DOCUMENTO,
	HIJOS_BOOLEAN,CANT_HIJOS,ESTADO_CIVIL,
	DIRECCION,GOOGLE_MAPS,
	OCUPACION, CARGO,
	SEGURO_VIDA_LEY,
	SEGURO_FECHA_INICIO,
	SEGURO_FECHA_VENCIMIENTO
ORDER BY C.ID_PERSONA ASC;

SELECT * FROM DATOS_CLIENTES_RECURSOS_HUMANOS;
select * from colaboradores;
UPDATE colaboradores SET ESTADO = 0 WHERE ID_PERSONA IN (4,5,8,9,10,11,12,13,14,18,22);
select * from productos;
SELECT DISTINCT(TIPO_PRODUCTO) FROM productos;