###############################################
-- VENTAS
###############################################
DROP PROCEDURE IF EXISTS VENTAS;
DELIMITER $$;
CREATE PROCEDURE VENTAS(IN METHOD VARCHAR(50), IN ID INT)
BEGIN
	IF METHOD = "LISTADO_VENTAS" THEN
		SELECT V.ID_VENTA, C.CLIENTE,V.FECHA, V.CLASIFICACION, V.ASESOR, V.N_COMPROBANTE, R.REGION, 
		D.DISTRITO, L.LUGAR AS LUGAR, V.SALIDA_DE_PEDIDO, V.OBSERVACIONES,P.CANCELADO, P.ESTADO
		FROM ventas as V
		-- Join con clientes
		inner join cliente as C
		ON V.ID_CLIENTE = C.ID_CLIENTE
		-- Join con region
		left join region as R
		on R.ID = V.ID_REGION
		-- join con distrito
		left join distrito AS D
		ON D.ID = V.ID_DISTRITO
		-- join con pagos
		left join pagos AS P
		ON P.ID_VENTA = V.ID_VENTA
        -- join con lugar
        left join lugar as L
        ON V.ID_LUGAR = L.ID
		WHERE V.ESTADO = 1
		ORDER BY V.ID_VENTA DESC
		LIMIT 100;
	ELSEIF METHOD = "VENTAS_NAVIDAD" THEN
    SELECT * FROM clientes_navidad_2025;
    ELSEIF METHOD = "VENTAS_ZEUS" THEN
		SELECT * FROM vista_ventas_general
        WHERE ASESOR = "ZEUS"
        ORDER BY ID_VENTA DESC;
    ELSEIF METHOD = "PAGOS_ID" THEN
		SELECT P.ID_PAGO, V.N_COMPROBANTE, COMPROBANTE, TIPO_DE_PAGO, FECHA_DE_PAGO, REGULARIZADO, CANCELADO, P.ESTADO
		from ventas as V
		inner join pagos as P
		ON V.ID_VENTA = P.ID_VENTA
		WHERE V.ID_VENTA = ID;
	ELSEIF METHOD = "DETALLE_PRODUCTOS" THEN
		SELECT D.ID_DETALLE, D.N_COMPROBANTE, D.CODIGO,D.PRODUCTO, D.CANTIDAD, D.PRECIO_VENTA, D.TOTAL
		FROM ventas as V
		inner join detalle_venta as D
		ON V.ID_VENTA = D.ID_VENTA
		WHERE V.ID_VENTA = ID
        AND D.ESTADO = 1;
	ELSEIF METHOD = "DISTRITO" THEN
		SELECT d.ID, d.DISTRITO FROM distrito as d;
	ELSEIF METHOD = "REGION" THEN
		SELECT r.ID, r.REGION FROM region as r;
	ELSEIF METHOD = "LUGAR" THEN
		SELECT l.ID,l.LUGAR FROM lugar as l WHERE ACTIVO = "SI";
	ELSEIF METHOD = "PROFORMAS_PAGADAS" THEN
		SET @ID := ID;
		WITH 
		id_comprobante AS (
			SELECT N_COMPROBANTE FROM ventas WHERE ID_VENTA = @ID
		),
		total AS (
			SELECT SUM(TOTAL) FROM detalle_venta AS det WHERE det.ID_VENTA = @ID
		)
	SELECT 
		R.NOMBRE,
		D.COMPROBANTES,
		D.MONTO,
		D.MEDIO_DE_PAGO,
		D.FECHA_REGULARIZACION,
		D.VALIDACION
	FROM ventas as V
	INNER JOIN detalle_regularizacion as D
	ON V.N_COMPROBANTE = D.COMPROBANTES
	INNER JOIN regularizacion AS R
		ON R.ID_REGULARIZACION = D.ID_REGULARIZACION
	WHERE V.ID_VENTA = @ID
	  AND D.ESTADO = 1;
	ELSEIF METHOD = "COMPROBANTES_SIN_CANCELAR" THEN
		SELECT * FROM vista_comprobantes_sin_cancelar
        ORDER BY ID_VENTA DESC;
    END IF;
END $$;
DELIMITER ;
-- CALL VENTAS('LUGAR',1);
CALL VENTAS('VENTAS_ZEUS',1);
-- AND (C.CLIENTE LIKE '%F 87%' OR V.N_COMPROBANTE LIKE '%F 87%')


DROP PROCEDURE IF EXISTS REPORTES;
DELIMITER $$
CREATE PROCEDURE REPORTES(IN min_mes INT, IN max_mes INT, IN yearr INT, IN METHOD VARCHAR(50))
BEGIN
	IF METHOD = "REGULARIZACION" THEN
		SELECT re.NOMBRE,det.COMPROBANTES, det.MONTO,det.MEDIO_DE_PAGO,det.ASESOR,det.FECHA_REGULARIZACION, det.OBSERVACION,det.VALIDACION
		from detalle_regularizacion as det INNER JOIN regularizacion as re
		ON det.ID_REGULARIZACION = re.ID_REGULARIZACION
		WHERE MONTH(det.FECHA_REGULARIZACION) >= min_mes and MONTH(det.FECHA_REGULARIZACION)< max_mes and YEAR(det.FECHA_REGULARIZACION)= yearr
		and ESTADO=1
		ORDER BY det.FECHA_REGULARIZACION DESC;
	ELSEIF METHOD = "VENTAS" THEN
		-- Reporte de ventas
		SELECT C.CLIENTE,V.FECHA, V.CLASIFICACION, V.ASESOR, V.N_COMPROBANTE, R.REGION, DIS.DISTRITO, L.LUGAR AS LUGAR, V.SALIDA_DE_PEDIDO, V.OBSERVACIONES,
		P.CANCELADO, P.REGULARIZADO, P.ESTADO, P.TIPO_DE_PAGO, P.FECHA_DE_PAGO,
		DET.CODIGO, DET.PRODUCTO, DET.CANTIDAD, DET.PRECIO_VENTA, DET.TOTAL
		FROM ventas AS V
		-- join con pagos
		inner join pagos as P
		on V.ID_VENTA = P.ID_VENTA
		-- join con productos comprados
		inner join detalle_venta as DET
		ON V.ID_VENTA = DET.ID_VENTA
		-- join con clientes
		inner join cliente as C
		ON C.ID_CLIENTE = V.ID_CLIENTE
		-- join con region
		left join region as R
		ON R.ID = V.ID_REGION
		-- join con distrito
		left join distrito as DIS
		ON DIS.ID = V.ID_DISTRITO
        -- join con lugar
        left join lugar as L
        ON L.ID = V.ID_LUGAR

		-- filtros
		WHERE V.ESTADO = 1
        AND
        DET.ESTADO = 1
		AND
		(MONTH(V.FECHA) >= min_mes and MONTH(V.FECHA)< max_mes and YEAR(V.FECHA)= yearr)
        AND
        (V.ASESOR <> "IMPORT ZEUS")
		ORDER BY V.FECHA DESC;
	END IF;
END $$;
DELIMITER ;

CALL REPORTES(6,7,2025,'VENTAS');

DROP PROCEDURE IF EXISTS METRICAS;
DELIMITER $$;
CREATE PROCEDURE METRICAS (IN METHOD VARCHAR(50), IN VARIABLE VARCHAR(20))
BEGIN
	IF METHOD = "COMPROBANTES_SIN_CANCELAR" THEN
		SELECT * FROM vista_comprobantes_sin_cancelar
        WHERE ASESOR = (SELECT NOMBRE FROM colaboradores WHERE usuario = VARIABLE)
        ORDER BY ID_VENTA DESC;
	ELSEIF METHOD = "TOTAL_POR_MES" THEN
			SELECT MONTH(V.FECHA),V.ASESOR,SUM(DET.TOTAL) as TOTAL
			FROM ventas AS V
			-- join con pagos
			inner join pagos as P
			on V.ID_VENTA = P.ID_VENTA
			-- join con productos comprados
			inner join detalle_venta as DET
			ON V.ID_VENTA = DET.ID_VENTA
			-- join con clientes
			inner join cliente as C
			ON C.ID_CLIENTE = V.ID_CLIENTE
			-- join con region
			left join region as R
			ON R.ID = V.ID_REGION
			-- join con distrito
			left join distrito as DIS
			ON DIS.ID_DISTRITO = V.ID_DISTRITO
			-- filtros
			WHERE V.ESTADO = 1
			AND
			  DET.ESTADO = 1
				AND P.ESTADO in ("COMPLETADO", null)
				  AND V.ASESOR = (SELECT NOMBRE FROM colaboradores WHERE usuario = VARIABLE)
			GROUP BY MONTH(V.FECHA),V.ASESOR
		ORDER BY MONTH(V.FECHA) DESC;
	END IF;
END $$;
DELIMITER ;
CALL METRICAS("TOTAL_POR_MES","hervinzeus");
CALL METRICAS("TOTAL_POR_MES","zeus");
CALL METRICAS("COMPROBANTES_SIN_CANCELAR","hervinzeus");


DROP PROCEDURE IF EXISTS BUSQUEDA;
DELIMITER $$;
CREATE PROCEDURE BUSQUEDA(IN METHOD VARCHAR(50), IN VARIABLE VARCHAR(10))
BEGIN
	IF METHOD = "CLIENTE" THEN
		SELECT * FROM vista_ventas_general
        WHERE ID_CLIENTE = VARIABLE
		ORDER BY ID_VENTA DESC;
	ELSEIF METHOD = "COMPROBANTE" THEN
		SELECT * FROM vista_ventas_general
        WHERE N_COMPROBANTE LIKE CONCAT("%",VARIABLE,"%")
		ORDER BY ID_VENTA DESC;
    END IF;
END $$;
DELIMITER ;

CALL BUSQUEDA("COMPROBANTE", "F 9640");
CALL BUSQUEDA("CLIENTE", '200');


CREATE TABLE auditoria_ventas(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	ID_VENTA INT REFERENCES ventas (ID_VENTA),
	ID_COLABORADOR INT REFERENCES colaboradores (ID_PERSONA),
	ACCION ENUM ('UPDATE','DELETE'),
	FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATOS_ANTERIORES JSON,
    DATOS_RECIENTES JSON
);
CREATE TABLE auditoria_regularizacion(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	ID_COLABORADOR INT REFERENCES colaboradores (ID_PERSONA),
	FECHA_REGISTRO TIMESTAMP DEFAULT current_timestamp,
    DATOS_ANTERIORES JSON,
    DATOS_RECIENTES JSON
);