###############################################
-- VISTAS
###############################################
select * from vista_ventas_general
where N_COMPROBANTE = "F 9640"
order by ID_VENTA desc;
DROP VIEW IF EXISTS vista_ventas_general;
CREATE VIEW vista_ventas_general AS
SELECT V.ID_CLIENTE, V.ID_VENTA, C.CLIENTE,V.FECHA, V.CLASIFICACION, V.ASESOR, V.N_COMPROBANTE, R.REGION, 
		D.DISTRITO, L.LUGAR AS LUGAR, V.SALIDA_DE_PEDIDO, V.OBSERVACIONES,P.CANCELADO, P.ESTADO
		FROM ventas as V
		-- Join con clientes
		inner join cliente as C
		ON V.ID_CLIENTE = C.ID_CLIENTE
		-- Join con region
		left join region as R
		on R.ID = V.ID_REGION
		-- join con distrito
		left join distrito AS D
		ON D.ID = V.ID_DISTRITO
		-- join con pagos
		left join pagos AS P
		ON P.ID_VENTA = V.ID_VENTA
        -- join con lugar
        left join lugar as L
        ON V.ID_LUGAR = L.ID
		WHERE V.ESTADO = 1;
        
DROP VIEW IF EXISTS vista_comprobantes_sin_cancelar;
CREATE VIEW vista_comprobantes_sin_cancelar AS
-- LISTADO DE FACTURAS SIN PAGAR
			-- script para obtener los pagos totales de los comprobantes válidos y no eliminados
			-- eliminar el limit y order by
			WITH ABONADO AS (
			  SELECT SUM(DET.MONTO) AS MONTO,DET.COMPROBANTES
			  FROM detalle_regularizacion DET
			  WHERE ESTADO = 1 AND VALIDACION = "VALIDO"
			  GROUP BY DET.COMPROBANTES
			),MONTO_TOTAL AS(
        SELECT N_COMPROBANTE, SUM(TOTAL) as MONTO_TOTAL FROM detalle_venta
        WHERE ESTADO = 1
        GROUP BY N_COMPROBANTE
      ),
			VENTAS AS (
			SELECT V.ID_VENTA, C.CLIENTE,V.FECHA, V.ASESOR, V.N_COMPROBANTE, R.REGION, 
					L.LUGAR AS LUGAR,P.CANCELADO, P.ESTADO, P.TIPO_DE_PAGO as CONDICION_PAGO
					FROM ventas as V
					-- Join con clientes
					inner join cliente as C
					ON V.ID_CLIENTE = C.ID_CLIENTE
					-- Join con region
					left join region as R
					on R.ID = V.ID_REGION
					-- join con pagos
					left join pagos AS P
					ON P.ID_VENTA = V.ID_VENTA
					-- join con lugar
					left join lugar as L
					ON L.ID = V.ID_LUGAR
					WHERE V.ESTADO = 1 AND P.CANCELADO = "NO" AND (P.ESTADO IS NULL OR P.ESTADO="COMPLETADO")
					ORDER BY FECHA DESC
			), TABLA AS(
			-- script para unir ambas tablas creadas temporalmente
			SELECT V.ID_VENTA, V.CLIENTE,V.FECHA, V.ASESOR, V.N_COMPROBANTE, V.REGION, 
					V.LUGAR,V.CANCELADO, M.MONTO_TOTAL,A.MONTO as TOTAL_ABONADO, CONDICION_PAGO
      FROM VENTAS AS V
      -- join con el monto abonado
			left JOIN ABONADO AS A
			ON V.N_COMPROBANTE = A.COMPROBANTES
      -- join con el total a abonar
      left join MONTO_TOTAL as M
      ON M.N_COMPROBANTE = V.N_COMPROBANTE
      )
      SELECT ID_VENTA,FECHA,  ASESOR ,REGION, LUGAR, CONDICION_PAGO, N_COMPROBANTE, 
      CLIENTE,MONTO_TOTAL, TOTAL_ABONADO, (MONTO_TOTAL-TOTAL_ABONADO) as POR_ABONAR
      FROM TABLA;


########################
-- CAMPAÑA NAVIDEÑA
########################
DROP VIEW IF EXISTS clientes_navidad_2025;
CREATE VIEW clientes_navidad_2025 AS
WITH clientes_compra AS(
  SELECT V.ID_CLIENTE, SUM(DET.TOTAL) AS TOTAL
  FROM ventas AS V
  -- join para el total
  INNER JOIN detalle_venta as DET
  ON V.ID_VENTA = DET.ID_VENTA
  -- join para excluir ventas no pasables
  INNER JOIN pagos AS P
  ON P.ID_VENTA = V.ID_VENTA
  WHERE V.ESTADO = 1 AND (P.ESTADO = "COMPLETADO" OR P.ESTADO = "" OR P.ESTADO IS NULL)
  AND YEAR(V.FECHA) = 2025
  GROUP BY V.ID_CLIENTE
)

(
  SELECT CLI.cliente, C.TOTAL, "TOP >150K" AS CATEGORIA FROM clientes_compra AS C
  INNER JOIN cliente AS CLI
  ON C.ID_CLIENTE = CLI.ID_CLIENTE
  WHERE TOTAL >= 150000
  ORDER BY TOTAL DESC
)

UNION ALL

(
  SELECT CLI.cliente, C.TOTAL, "TOP >50K" AS CATEGORIA FROM clientes_compra AS C
  INNER JOIN cliente AS CLI
  ON C.ID_CLIENTE = CLI.ID_CLIENTE
  WHERE TOTAL >= 50000 AND TOTAL <150000
  ORDER BY TOTAL DESC
  LIMIT 10
)

UNION ALL
(
  SELECT CLI.cliente, C.TOTAL, "TOP <50k" AS CATEGORIA FROM clientes_compra AS C
  INNER JOIN cliente AS CLI
  ON C.ID_CLIENTE = CLI.ID_CLIENTE
  WHERE TOTAL < 50000
  ORDER BY TOTAL DESC
  LIMIT 10
)

SELECT * FROM clientes_navidad_2025;
SET @ID = 2;
################################################
################################################
################################################
DROP VIEW IF EXISTS clientes_navidad_2025;
CREATE VIEW clientes_navidad_2025 AS
WITH CLIENTES_ACTEGORIA AS (
	WITH clientes_compra AS(
	  SELECT 
		CASE 
			WHEN V.ID_CLIENTE IN (16, 43) THEN 16
            WHEN V.ID_CLIENTE IN (44, 68) THEN 68
			ELSE V.ID_CLIENTE
		END AS ID_CLIENTE,
		SUM(DET.TOTAL) AS TOTAL
	FROM ventas AS V
	INNER JOIN detalle_venta AS DET
		ON V.ID_VENTA = DET.ID_VENTA
	INNER JOIN pagos AS P
		ON P.ID_VENTA = V.ID_VENTA
	WHERE 
		V.ESTADO = 1
		AND (P.ESTADO = 'COMPLETADO' OR P.ESTADO = '' OR P.ESTADO IS NULL)
		AND YEAR(V.FECHA) = 2025
	GROUP BY 
		CASE 
			WHEN V.ID_CLIENTE IN (16, 43) THEN 16
            WHEN V.ID_CLIENTE IN (44, 68) THEN 68
			ELSE V.ID_CLIENTE
		END
	)
	SELECT ID_CLIENTE, TOTAL,
	CASE 
		-- CASE PARA "TOP >150K"
		WHEN TOTAL >= 150000 THEN "TRINEOS DORADOS"
		-- CASE PARA "TOP >50K"
		WHEN TOTAL >= 50000 AND TOTAL <150000 THEN "ESTRELLAS POLARES"
		-- CASE PARA "TOP <50k"
		WHEN TOTAL < 50000 THEN "DUENDES EN ASCENSO"
	END AS CATEGORIA
	FROM clientes_compra
)
  (SELECT CLI.cliente, C.TOTAL,CATEGORIA,
  CASE
	-- PRIMERA SECCION
    WHEN C.TOTAL >= 650000 THEN 1000000
    WHEN C.TOTAL < 650000 AND C.TOTAL >= 370000 THEN 650000
    WHEN C.TOTAL < 370000 AND C.TOTAL >= 300000 THEN 370000
    WHEN C.TOTAL < 300000 AND C.TOTAL >= 180000 THEN 300000
    WHEN C.TOTAL < 180000 AND C.TOTAL >= 150000 THEN 180000
END AS SUB_CATEGORIA
  FROM CLIENTES_ACTEGORIA AS C
  INNER JOIN cliente AS CLI
  ON C.ID_CLIENTE = CLI.ID_CLIENTE
  WHERE CATEGORIA = "TRINEOS DORADOS"
  ORDER BY TOTAL DESC
  LIMIT 10
)
UNION ALL 
(
SELECT CLI.cliente, C.TOTAL, CATEGORIA,
  CASE
	-- PRIMERA SECCION
    WHEN C.TOTAL >= 120000 THEN 150000
    WHEN C.TOTAL < 120000 AND C.TOTAL >= 100000 THEN 120000
    WHEN C.TOTAL < 100000 AND C.TOTAL >= 85000 THEN 100000
    WHEN C.TOTAL < 85000 AND C.TOTAL >= 70000 THEN 85000
    WHEN C.TOTAL < 70000 AND C.TOTAL >= 50000 THEN 70000
END AS SUB_CATEGORIA
  FROM CLIENTES_ACTEGORIA AS C
  INNER JOIN cliente AS CLI
  ON C.ID_CLIENTE = CLI.ID_CLIENTE
  WHERE CATEGORIA = "ESTRELLAS POLARES"
  ORDER BY TOTAL DESC
  LIMIT 10
)
UNION ALL
(
SELECT CLI.cliente, C.TOTAL,CATEGORIA, 50000 as SUB_CATEGORIA FROM CLIENTES_ACTEGORIA AS C
  INNER JOIN cliente AS CLI
  ON C.ID_CLIENTE = CLI.ID_CLIENTE
  WHERE CATEGORIA = "DUENDES EN ASCENSO"
  ORDER BY TOTAL DESC
  LIMIT 10
);
SELECT * FROM clientes_navidad_2025;