USE Zeus_Safety_Data_Integration;
CREATE TABLE PERMISOS_LABORALES(
ID INT PRIMARY KEY AUTO_INCREMENT,
FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ID_AREA_RECEPCION INT REFERENCES AREAS(ID),
ID_COLABORADOR INT REFERENCES colaboradores(ID_PERSONA),
FECHA_INICIO DATETIME,
FECHA_FIN DATETIME,
TIPO_PERMISO VARCHAR(30),
MOTIVO TEXT,
ESTADO_SOLICITUD VARCHAR(30),
HORAS_SOLICITADAS DOUBLE(10,2),
HORAS_CUMPLIDAS DOUBLE(10,2),
HORAS_FALTANTESS DOUBLE(10,2),
ESTADO_COMPLETADO VARCHAR(30)
);
ALTER TABLE PERMISOS_LABORALES
MODIFY COLUMN TIPO_PERMISO VARCHAR(100);

CREATE TABLE PERMISOS_ARCHIVOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_PERMISO INT REFERENCES PERMISOS_LABORALES(ID),
URL_ARCHIVO TEXT
);

CREATE TABLE IF NOT EXISTS RESPUESTAS(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_PERMISO INT REFERENCES PERMISOS_LABORALES(ID),
FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
RESPUESTA TEXT,
ID_RESPONDIDO_POR INT REFERENCES colaboradores(ID_PERSONA)
);

select ID_PERSONA, CONCAT(NOMBRE," ", APELLIDO," ", SEGUNDO_NOMBRE) AS NOMBRE from colaboradores 
WHERE ESTADO = 1
order by ID_PERSONA desc;