DROP PROCEDURE IF EXISTS PERMISOS_LABORALES;
DELIMITER $$;
CREATE PROCEDURE PERMISOS_LABORALES(IN METHOD VARCHAR(30), IN VARIABLE VARCHAR(30))
BEGIN
	IF METHOD = "LISTADO_COLABORADOR" THEN
		select P.ID, P.FECHA_REGISTRO, A.NOMBRE, P.FECHA_INICIO, P.FECHA_FIN, P.TIPO_PERMISO, P.MOTIVO, 
		P.ESTADO_SOLICITUD, P.HORAS_SOLICITADAS, P.HORAS_CUMPLIDAS, P.HORAS_FALTANTESS,
		JSON_ARRAYAGG(JSON_OBJECT('url', F.URL_ARCHIVO)) AS ARCHIVOS
		from PERMISOS_LABORALES P
		inner join AREAS AS A
		ON P.ID_AREA_RECEPCION = A.ID
		INNER JOIN colaboradores AS C
		ON C.ID_PERSONA = P.ID_COLABORADOR
		INNER JOIN PERMISOS_ARCHIVOS as F
		ON F.ID_PERMISO = P.ID
		WHERE P.ID_COLABORADOR = (SELECT ID_PERSONA WHERE USUARIO = VARIABLE)
		GROUP BY
		P.ID, P.FECHA_REGISTRO, A.NOMBRE, P.FECHA_INICIO, P.FECHA_FIN, P.TIPO_PERMISO, P.MOTIVO, 
		P.ESTADO_SOLICITUD, P.HORAS_SOLICITADAS, P.HORAS_CUMPLIDAS, P.HORAS_FALTANTESS
		;
    END IF;
END $$;
DELIMITER ;
CALL PERMISOS_LABORALES("LISTADO_COLABORADOR","joseph");

select * from AREAS;
select count(*) from PERMISOS_LABORALES;
select * from PERMISOS_LABORALES order by id desc;
select * from PERMISOS_ARCHIVOS;

select C.NOMBRE, P.ID, P.FECHA_REGISTRO, A.NOMBRE, P.FECHA_INICIO, P.FECHA_FIN, P.TIPO_PERMISO, P.MOTIVO, 
P.ESTADO_SOLICITUD, P.HORAS_SOLICITADAS, P.HORAS_CUMPLIDAS, P.HORAS_FALTANTESS,
JSON_ARRAYAGG(JSON_OBJECT('url', F.URL_ARCHIVO)) AS ARCHIVOS
from PERMISOS_LABORALES P
LEFT join AREAS AS A
ON P.ID_AREA_RECEPCION = A.ID
INNER JOIN colaboradores AS C
ON C.ID_PERSONA = P.ID_COLABORADOR
LEFT JOIN PERMISOS_ARCHIVOS as F
ON F.ID_PERMISO = P.ID
GROUP BY
P.ID, P.FECHA_REGISTRO, A.NOMBRE, P.FECHA_INICIO, P.FECHA_FIN, P.TIPO_PERMISO, P.MOTIVO, 
P.ESTADO_SOLICITUD, P.HORAS_SOLICITADAS, P.HORAS_CUMPLIDAS, P.HORAS_FALTANTESS
;

UPDATE PERMISOS_LABORALES SET TIPO_PERMISO = "", MOTIVO = "" WHERE ID = 1;