DROP PROCEDURE IF EXISTS PERMISOS_LABORALES;
DELIMITER $$;
CREATE PROCEDURE PERMISOS_LABORALES(IN METHOD VARCHAR(30), IN VARIABLE VARCHAR(30))
BEGIN
	IF METHOD = "LISTADO_COLABORADOR" THEN
		select P.ID, P.FECHA_REGISTRO, A.NOMBRE, P.FECHA_INICIO, P.FECHA_FIN, P.TIPO_PERMISO, P.MOTIVO, P.ESTADO_SOLICITUD, P.HORAS_SOLICITADAS, P.HORAS_CUMPLIDAS, P.HORAS_FALTANTESS
		from PERMISOS_LABORALES P
		inner join AREAS AS A
		ON P.ID_AREA_RECEPCION = A.ID
		INNER JOIN colaboradores AS C
		ON C.ID_PERSONA = P.ID_COLABORADOR
		WHERE P.ID_COLABORADOR = (SELECT ID_PERSONA WHERE USUARIO = VARIABLE)
		;
    END IF;
END $$;
DELIMITER ;
CALL PERMISOS_LABORALES("LISTADO_COLABORADOR","eliaszeus");

select * from AREAS;
select * from PERMISOS_LABORALES;

select P.ID, P.FECHA_REGISTRO, A.NOMBRE, P.FECHA_INICIO, P.FECHA_FIN, P.TIPO_PERMISO, P.MOTIVO, P.ESTADO_SOLICITUD, P.HORAS_SOLICITADAS, P.HORAS_CUMPLIDAS, P.HORAS_FALTANTESS
from PERMISOS_LABORALES P
inner join AREAS AS A
ON P.ID_AREA_RECEPCION = A.ID
INNER JOIN colaboradores AS C
ON C.ID_PERSONA = P.ID_COLABORADOR
WHERE P.ID_COLABORADOR = (SELECT ID_PERSONA WHERE USUARIO = "eliaszeus")
;