###############################################
-- REGULARIZACION
###############################################
SHOW CREATE PROCEDURE REGULARIZACION;

DROP PROCEDURE IF EXISTS REGULARIZACION;
DELIMITER $$;
CREATE PROCEDURE REGULARIZACION(IN METHOD varchar(50), IN ID varchar(50))
BEGIN
	IF METHOD = "LISTADO_GENERAL" THEN
		WITH total_bloque as(
			SELECT ID_REGULARIZACION,count(ID_DETALLE) as cant from detalle_regularizacion
			GROUP BY ID_REGULARIZACION)
                    
		SELECT re.ID_REGULARIZACION,NOMBRE,FECHA,EFECTIVO_INDICADO,t.cant as Cantidad
		FROM regularizacion as re
		INNER JOIN total_bloque as t
		ON re.ID_REGULARIZACION = t.ID_REGULARIZACION
		ORDER BY FECHA DESC
		limit 10;
        
    ELSEIF METHOD = "LISTADO_ID" THEN
		SELECT det.ID_DETALLE,re.NOMBRE,det.COMPROBANTES, det.FECHA_REGULARIZACION, det.MONTO, det.ASESOR, det.MEDIO_DE_PAGO, det.OBSERVACION, det.VALIDACION
        FROM regularizacion as re
		inner join detalle_regularizacion as det
		ON re.ID_REGULARIZACION = det.ID_REGULARIZACION
		WHERE ESTADO=1 and det.ID_REGULARIZACION=ID
		ORDER BY det.FECHA_REGULARIZACION DESC;
        
	ELSEIF METHOD = "BUSQUEDA"  THEN
		SELECT det.ID_DETALLE,re.NOMBRE,det.COMPROBANTES, det.FECHA_REGULARIZACION, det.MONTO, det.ASESOR, det.MEDIO_DE_PAGO, det.OBSERVACION FROM regularizacion as re
		inner join detalle_regularizacion as det
		ON re.ID_REGULARIZACION = det.ID_REGULARIZACION
		WHERE ESTADO=1 and det.COMPROBANTES= ID
		ORDER BY det.FECHA_REGULARIZACION DESC;
    END IF;
END $$;
DELIMITER ;

CALL REGULARIZACION("LISTADO_ID","REG_1746040735776_9849");
CALL REGULARIZACION("BUSQUEDA","F 9556");