CREATE TABLE IF NOT EXISTS AUDITORIA_LOGIN (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_COLABORADOR INT,
    FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auditoria_colaborador
        FOREIGN KEY (ID_COLABORADOR) REFERENCES colaboradores(ID_PERSONA)
) ENGINE=InnoDB;
INSERT INTO AUDITORIA_LOGIN(ID_COLABORADOR) VALUES ((SELECT ID_PERSONA from colaboradores where usuario = "hervinzeus"));

Set time_zone = "America/Lima";
SELECT * FROM AUDITORIA_LOGIN;

CREATE INDEX idx_auditoria_usuario_fecha
ON AUDITORIA_LOGIN (ID_COLABORADOR, FECHA_HORA);