CREATE TABLE IF NOT EXISTS AUDITORIA_LOGIN (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_COLABORADOR INT,
    FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auditoria_colaborador
        FOREIGN KEY (ID_COLABORADOR) REFERENCES colaboradores(ID_PERSONA)
) ENGINE=InnoDB;
