DROP PROCEDURE IF EXISTS AUDITORIA_LOGIN_SP;
DELIMITER $$
CREATE PROCEDURE AUDITORIA_LOGIN_SP(
    IN P_METHOD VARCHAR(50),
    IN P_ID_GENERAL VARCHAR(10),
    IN P_LIMIT INT,
    IN P_OFFSET INT
)
BEGIN
    IF P_METHOD = 'LOGIN' THEN
        SELECT A.ID, C.NOMBRE, C.APELLIDO, A.FECHA_HORA
        FROM AUDITORIA_LOGIN A
        INNER JOIN colaboradores C 
            ON C.ID_PERSONA = A.ID_COLABORADOR
        WHERE C.ESTADO IN (1,0)
        ORDER BY A.FECHA_HORA DESC
        LIMIT P_LIMIT OFFSET P_OFFSET;

    ELSEIF P_METHOD = 'LOGIN_USUARIO' THEN
        SELECT A.ID, C.NOMBRE, C.APELLIDO, A.FECHA_HORA
        FROM AUDITORIA_LOGIN A
        INNER JOIN colaboradores C 
            ON C.ID_PERSONA = A.ID_COLABORADOR
        WHERE C.ESTADO IN (1,0)
          AND C.ID_PERSONA = P_ID_GENERAL
        ORDER BY A.FECHA_HORA DESC
        LIMIT P_LIMIT OFFSET P_OFFSET;
    END IF;
END$$
DELIMITER ;

CALL AUDITORIA_LOGIN_SP('LOGIN_USUARIO', 1, 60, 0);
CALL AUDITORIA_LOGIN_SP('LOGIN', 1, 250, 0);

SELECT * from colaboradores order by id_persona limit 5 offset 0;
SELECT * from colaboradores order by id_persona limit 10 offset 10;
SELECT * from colaboradores order by id_persona desc limit 1;