DROP PROCEDURE IF EXISTS AUDITORIA_LOGIN;
DELIMITER $$;
CREATE PROCEDURE AUDITORIA_LOGIN(IN METHOD VARCHAR(50))
BEGIN
	IF METHOD = "LOGIN" THEN
		Set time_zone = "America/Lima";
		SELECT A.ID, C.NOMBRE, C.APELLIDO, A.FECHA_HORA FROM AUDITORIA_LOGIN AS A
        INNER JOIN colaboradores as C
        ON C.ID_PERSONA = A.ID_COLABORADOR
        WHERE C.ESTADO IN (1,0) -- 2 para usuarios de prueba
        ORDER BY A.FECHA_HORA DESC
        LIMIT 60
        -- WHERE MONTH(A.FECHA_HORA) = MONTH(NOW)
        ;
    END IF;
END $$;
DELIMITER ;
CALL AUDITORIA_LOGIN("LOGIN")