use Zeus_Safety_Data_Integration;
DROP PROCEDURE IF EXISTS subvistas_colaborador;
DELIMITER $$;
CREATE PROCEDURE subvistas_colaborador(IN METHOD VARCHAR(30),IN VARIABLE VARCHAR(30))
BEGIN
	IF METHOD = "s" THEN
		-- Script para obtener todas las subvistas por el nombre de usuario:
		SELECT ID_SUB_VISTAS, SB.NOMBRE FROM SUB_VISTAS_COLABORADORES AS VC
		INNER JOIN SUB_VISTAS AS SB
		ON VC.ID_SUB_VISTAS = SB.ID
		WHERE VC.ESTADO = 1 AND ID_COLABORADOR=(SELECT ID_PERSONA FROM colaboradores WHERE USUARIO=VARIABLE);
    END IF;
END $$;
DELIMITER ;
CALL subvistas_colaborador("joseph");

-- Script para obtener todas las subvistas que tiene un área
SELECT SB.ID, SB.NOMBRE,A.NOMBRE AS AREA FROM SUB_VISTAS AS SB
INNER JOIN AREAS AS A
ON SB.ID_AREA = A.ID
WHERE A.NOMBRE = "VENTAS";

UPDATE colaboradores SET ID_ROL = 2 where ID_PERSONA = 6;
SELECT NOMBRE from colaboradores WHERE ID_ROL = 1;


########################################
-- PROCEDIMIENTO URL PAGE
########################################
DROP PROCEDURE IF EXISTS OBTENER_URL;
DELIMITER $$
CREATE PROCEDURE OBTENER_URL(IN ID INT, IN NOMBRE_SUB_VISTA VARCHAR(50), OUT URL_RESULT VARCHAR(255))
BEGIN
	-- declaramos el area
    DECLARE URL VARCHAR(255);
    DECLARE AREA VARCHAR(50);
    
    -- obtenemos el área en base al id
    SELECT A.ID  INTO AREA 
    FROM colaboradores AS C
	INNER JOIN AREAS AS A
	ON A.ID = C.AREA_PRINCIPAL
	WHERE CULMINACION = "ACTUALMENTE"
	AND C.ESTADO = 1
	AND ID_PERSONA=ID;
    
    -- Asignamos valores a las variablees en base a la query
    SELECT SV.URL 
    INTO URL_RESULT
    FROM SUB_VISTAS as SV
	INNER JOIN AREAS as A
	ON SV.ID_AREA = A.ID
	WHERE SV.NOMBRE = NOMBRE_SUB_VISTA
    AND SV.ID_AREA=AREA; -- comparamos con la variable de área obtenida
END $$;
DELIMITER ;

call OBTENER_URL(1,"listado de importaciones",@url);
call OBTENER_URL(1,"LISTADO INCIDENCIA DE PROFORMAS",@url);
SELECT @url;


use Zeus_Safety_Data_Integration ;
########################################
-- PROCEDIMIENTO PERMISOS DE SUBVISTAS
########################################
DELIMITER $$
DROP PROCEDURE IF EXISTS PERMISOS;
CREATE PROCEDURE PERMISOS(IN METHOD VARCHAR(30), IN USERR VARCHAR(50))
BEGIN
	IF METHOD = "SUB_VISTAS" THEN
		SELECT B.ID,B.NOMBRE AS SUB_VISTA, A.NOMBRE AS AREA FROM SUB_VISTAS AS B
		INNER JOIN AREAS AS A
		ON B.ID_AREA = A.ID;
    ELSEIF METHOD = "SUB_VISTAS_PERMISOS" THEN
		SELECT F.ESTADO,B.NOMBRE, A.NOMBRE AS AREA FROM SUB_VISTAS_COLABORADORES AS F
		INNER JOIN SUB_VISTAS AS B
		ON F.ID_SUB_VISTAS = B.ID
		INNER JOIN AREAS AS A
		ON B.ID_AREA = A.ID
		WHERE F.ID_COLABORADOR= (SELECT ID_PERSONA FROM colaboradores WHERE USUARIO=USERR);
	ELSEIF METHOD = "MODULOS_PERMISOS" THEN
		SELECT a.NOMBRE 
        FROM MODULOS AS m 
		INNER JOIN AREAS AS a ON m.ID_AREA = a.ID 
		WHERE ID_COLABORADOR = (
		SELECT ID_PERSONA FROM colaboradores WHERE USUARIO=USERR
		)
		AND m.ESTADO=1;
    ELSEIF METHOD = "SUBVISTAS" THEN
		SELECT ID_SUB_VISTAS, SB.NOMBRE FROM SUB_VISTAS_COLABORADORES AS VC
		INNER JOIN SUB_VISTAS AS SB
		ON VC.ID_SUB_VISTAS = SB.ID
		WHERE VC.ESTADO = 1 AND ID_COLABORADOR=(SELECT ID_PERSONA FROM colaboradores WHERE USUARIO=USERR);
	END IF;
END $$
DELIMITER ;
CALL PERMISOS('MODULOS_PERMISOS','hervinzeus');
CALL PERMISOS('SUBVISTAS','joseph');
CALL PERMISOS('SUB_VISTAS','random');
-- crear un trigger al momento de insertar un colaborador
########################
-- UNIR IDS DE COLABORADORES
########################
DROP PROCEDURE IF EXISTS ELIMINAR_INSERTAR_SUB_VISTA;
DELIMITER $$;
CREATE PROCEDURE ELIMINAR_INSERTAR_SUB_VISTA(IN METHOD VARCHAR(30), IN IN_ID_COLABORADOR INT, IN IN_ID_SUB_VISTA INT)
BEGIN
	-- Declaramos una variable para filtrar
    DECLARE FILTRO INT;
	IF METHOD = "AÑADIR_SUB_VISTA" THEN
		SELECT ID INTO FILTRO FROM SUB_VISTAS_COLABORADORES
        WHERE ID_COLABORADOR = IN_ID_COLABORADOR AND ID_SUB_VISTAS = IN_ID_SUB_VISTA
        LIMIT 1;
        IF FILTRO IS NULL THEN
			INSERT INTO SUB_VISTAS_COLABORADORES(ID_COLABORADOR, ID_SUB_VISTAS) VALUES (IN_ID_COLABORADOR, IN_ID_SUB_VISTA);
		END IF;
    ELSEIF METHOD = "ELIMINAR_SUB_VISTA" THEN
		SET SQL_SAFE_UPDATES = 0;
		DELETE FROM SUB_VISTAS_COLABORADORES WHERE ID_COLABORADOR = IN_ID_COLABORADOR AND ID = IN_ID_SUB_VISTA;
        SET SQL_SAFE_UPDATES = 1;
    END IF;
END $$;
DELIMITER ;
CALL ELIMINAR_INSERTAR_SUB_VISTA("AÑADIR_SUB_VISTA");
CALL ELIMINAR_INSERTAR_SUB_VISTA("ELIMINAR_SUB_VISTA",6,40);
SELECT * FROM SUB_VISTAS_COLABORADORES WHERE ID_COLA;

INSERT INTO SUB_VISTAS(NOMBRE, ID_AREA) VALUES
("RECENCIA_CLIENTES",1),
("GESTION_CLIENTES",1),
("LISTADO_VENTAS",1),
("STOCK_PRECIOS",1);

################################################################################
################################################################################
-- NUEVOS PROCEDIMIENTOS
################################################################################
################################################################################
DROP PROCEDURE IF EXISTS COLABORADORES_LOGIN;
DELIMITER $$;
CREATE PROCEDURE COLABORADORES_LOGIN(IN METHOD INT, IN IN_USUARIO VARCHAR(30))
BEGIN
	IF METHOD == 1 THEN
		 SELECT CONTRASEÑA FROM colaboradores WHERE USUARIO = IN_USUARIO AND ESTADO = 1
    ELSEIF METHOD == 2 THEN
		SELECT NOW();
    ELSEIF METHOD == 3 THEN
		SELECT NOW();
    END IF
END
DELIMITER $$;

-- Consulta para obtener los roles de un colaborador                        
SELECT * FROM ROL;
SELECT * FROM colaboradores;

SELECT R.NOMBRE FROM ROL AS R
INNER JOIN colaboradores AS C
ON C.ID_ROL = R.ID
WHERE C.USUARIO = "joseph"
;

select * from colaboradores ORDER BY ID_PERSONA DESC limit 20;
INSERT INTO colaboradores(USUARIO, CONTRASEÑA2)
VALUES ("pablo","pablo123");
select * from colaboradores where nombre like "%eli%";