-- Script para obtener todas las subvistas que tiene un área
SELECT SB.ID, SB.NOMBRE,A.NOMBRE AS AREA FROM SUB_VISTAS AS SB
INNER JOIN AREAS AS A
ON SB.ID_AREA = A.ID
WHERE A.NOMBRE = "MARKETING";

UPDATE colaboradores SET ID_ROL = 2 where ID_PERSONA = 6;
SELECT NOMBRE from colaboradores WHERE ID_ROL = 1;
########################################
-- PROCEDIMIENTO URL PAGE
########################################
DROP PROCEDURE IF EXISTS OBTENER_URL;
DELIMITER $$
CREATE PROCEDURE OBTENER_URL(IN ID INT, IN NOMBRE_SUB_VISTA VARCHAR(50), OUT URL_RESULT VARCHAR(255))
BEGIN
	-- declaramos el area
    DECLARE URL VARCHAR(255);
    DECLARE AREA VARCHAR(50);
    
    -- obtenemos el área en base al id
    SELECT A.ID  INTO AREA 
    FROM colaboradores AS C
	INNER JOIN AREAS AS A
	ON A.ID = C.AREA_PRINCIPAL
	WHERE CULMINACION = "ACTUALMENTE"
	AND C.ESTADO = 1
	AND ID_PERSONA=ID;
    
    -- Asignamos valores a las variablees en base a la query
    SELECT SV.URL 
    INTO URL_RESULT
    FROM SUB_VISTAS as SV
	INNER JOIN AREAS as A
	ON SV.ID_AREA = A.ID
	WHERE SV.NOMBRE = NOMBRE_SUB_VISTA
    AND SV.ID_AREA=AREA; -- comparamos con la variable de área obtenida
END $$;
DELIMITER ;

call OBTENER_URL(1,"listado de importaciones",@url);
call OBTENER_URL(1,"LISTADO INCIDENCIA DE PROFORMAS",@url);
SELECT @url;


use Zeus_Safety_Data_Integration ;
########################################
-- PROCEDIMIENTO PERMISOS DE SUBVISTAS
########################################
DELIMITER $$
DROP PROCEDURE IF EXISTS PERMISOS;
CREATE PROCEDURE PERMISOS(IN METHOD VARCHAR(30), IN USERR VARCHAR(50))
BEGIN
	IF METHOD = "SUB_VISTAS" THEN
		SELECT B.ID,B.NOMBRE AS SUB_VISTA, A.NOMBRE AS AREA FROM SUB_VISTAS AS B
		INNER JOIN AREAS AS A
		ON B.ID_AREA = A.ID;
    ELSEIF METHOD = "SUB_VISTAS_PERMISOS" THEN
		SELECT F.ESTADO,B.NOMBRE, A.NOMBRE AS AREA FROM SUB_VISTAS_COLABORADORES AS F
		INNER JOIN SUB_VISTAS AS B
		ON F.ID_SUB_VISTAS = B.ID
		INNER JOIN AREAS AS A
		ON B.ID_AREA = A.ID
		WHERE F.ID_COLABORADOR= (SELECT ID_PERSONA FROM colaboradores WHERE USUARIO=USERR);
	ELSEIF METHOD = "MODULOS_PERMISOS" THEN
		SELECT a.NOMBRE 
        FROM MODULOS AS m 
		INNER JOIN AREAS AS a ON m.ID_AREA = a.ID 
		WHERE ID_COLABORADOR = (
		SELECT ID_PERSONA FROM colaboradores WHERE USUARIO=USERR
		)
		AND m.ESTADO=1;
    ELSEIF METHOD = "SUBVISTAS" THEN
		SELECT VC.ID, SB.NOMBRE, SB.URL FROM SUB_VISTAS_COLABORADORES AS VC
		INNER JOIN SUB_VISTAS AS SB
		ON VC.ID_SUB_VISTAS = SB.ID
		WHERE VC.ESTADO = 1 AND ID_COLABORADOR=(SELECT ID_PERSONA FROM colaboradores WHERE USUARIO=USERR);
	END IF;
END $$
DELIMITER ;

CALL PERMISOS('MODULOS_PERMISOS','sandrazeus');
CALL PERMISOS('SUBVISTAS','joseph');
SET @ID = 1;
-- crear un trigger al momento de insertar un colaborador
########################################
-- PROCEDIMIENTO COLABORADORES
########################################
-- Listado de procedimientos
DROP PROCEDURE IF EXISTS COLABORADORES_DATOS;
DELIMITER $$
CREATE PROCEDURE COLABORADORES_DATOS(in method varchar(50), in userr varchar(50))
BEGIN
	IF method = "LISTADO_NOTIFICACIONES" THEN
		SELECT N.ID, C.NOMBRE, TITULO, CUERPO, TIPO, URL_ACCION, ESTADO_LECTURA FROM NOTIFICACIONES AS N
		INNER JOIN colaboradores AS C
		ON C.ID_PERSONA = N.ID_COLABORADOR
		WHERE N.ESTADO = "1" and C.USUARIO=userr
        ORDER BY N.FECHA_CREACION DESC
        LIMIT 15;
    ELSEIF method = "LISTADO_COLABORADORES" THEN
		SELECT ID_PERSONA,NOMBRE, APELLIDO, AREA, CORREO, FECHA_NACIMIENTO
		FROM colaboradores WHERE CULMINACION = "ACTUALMENTE" AND ESTADO=1 ORDER BY ID_PERSONA ASC;
	elseif method = "COLABORADORES_INACTIVOS" THEN
		SELECT ID_PERSONA,NOMBRE, APELLIDO, AREA, CORREO, FECHA_NACIMIENTO
		FROM colaboradores WHERE CULMINACION = "ACTUALMENTE" AND ESTADO=0 ORDER BY ID_PERSONA ASC;
    ELSEIF method = "COLABORADORES" THEN
		SELECT ID_PERSONA,NOMBRE,AREA
		FROM colaboradores WHERE CULMINACION = "ACTUALMENTE" AND ESTADO=1 ORDER BY ID_PERSONA ASC;
    ELSEIF method = "NOTIFICACION_LEIDA" THEN
		SET time_zone = 'America/Lima';
		UPDATE NOTIFICACIONES SET ESTADO_LECTURA = 1, FECHA_LECTURA= now() WHERE ID = userr; -- user no es usuario, es el id entrante de la notificacion
    END IF;
END $$;
DELIMITER ;

CALL COLABORADORES_DATOS('LISTADO_NOTIFICACIONES','hervinzeus');
CALL COLABORADORES_DATOS('NOTIFICACION_LEIDA',1);
UPDATE NOTIFICACIONES SET ESTADO_LECTURA = 0 WHERE ID = 1;
UPDATE NOTIFICACIONES SET ESTADO_LECTURA = 0 WHERE ID = 3;

########################
-- UNIR IDS DE COLABORADORES
########################
DROP PROCEDURE IF EXISTS ELIMINAR_INSERTAR_SUB_VISTA;
DELIMITER $$;
CREATE PROCEDURE ELIMINAR_INSERTAR_SUB_VISTA(IN METHOD VARCHAR(30), IN IN_ID_COLABORADOR INT, IN IN_ID_SUB_VISTA INT)
BEGIN
	-- Declaramos una variable para filtrar
    DECLARE FILTRO INT;
	IF METHOD = "AÑADIR_SUB_VISTA" THEN
		SELECT ID INTO FILTRO FROM SUB_VISTAS_COLABORADORES
        WHERE ID_COLABORADOR = IN_ID_COLABORADOR AND ID_SUB_VISTAS = IN_ID_SUB_VISTA
        LIMIT 1;
        IF FILTRO IS NULL THEN
			INSERT INTO SUB_VISTAS_COLABORADORES(ID_COLABORADOR, ID_SUB_VISTAS) VALUES (IN_ID_COLABORADOR, IN_ID_SUB_VISTA);
		END IF;
    ELSEIF METHOD = "ELIMINAR_SUB_VISTA" THEN
		DELETE FROM SUB_VISTAS_COLABORADORES WHERE ID_COLABORADOR = IN_ID_COLABORADOR AND ID = IN_ID_SUB_VISTA;
    END IF;
END $$;
DELIMITER ;
CALL ELIMINAR_INSERTAR_SUB_VISTA("AÑADIR_SUB_VISTA");
CALL ELIMINAR_INSERTAR_SUB_VISTA("ELIMINAR_SUB_VISTA",6,40);
SELECT * FROM SUB_VISTAS_COLABORADORES WHERE ID_COLA;

INSERT INTO SUB_VISTAS(NOMBRE, ID_AREA) VALUES
("RECENCIA_CLIENTES",1),
("GESTION_CLIENTES",1),
("LISTADO_VENTAS",1),
("STOCK_PRECIOS",1);