CREATE TABLE IF NOT EXISTS SIMULACION_PROFORMAS(
ID INT PRIMARY KEY AUTO_INCREMENT,
FECHA_REGISTRO TIMESTAMP,
ID_ASESOR INT REFERENCES colaboradores(ID_PERSONA),
ID_REGISTRADO_POR VARCHAR(50), -- REFERENCES colaboradores(ID_PERSONA),
ALMACEN INT REFERENCES ALMACENES(ID),
N_PROFORMA VARCHAR(20) NOT NULL UNIQUE,
ARCHIVO_URL VARCHAR(255),
ESTADO CHAR(1) DEFAULT 1
);

CREATE TABLE SIMULACION_PROFORMAS_DETALLE(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_SIMULACION_PROFORMA INT REFERENCES SIMULACION_PROFORMA(ID),
ID_PRODUCTO INT REFERENCES PRODUCTOS(ID),
UNIDAD_MEDIDA VARCHAR(25),
CANTIDAD INT NOT NULL,
ESTADO CHAR(1) DEFAULT 1
);
#########################################################
CREATE OR REPLACE VIEW VISTA_PERMISOS_COLABORADORES AS
SELECT C.ID_PERSONA, C.NOMBRE, A.NOMBRE AS AREA, C.ID_ROL
from colaboradores as C
inner join AREAS AS A
ON C.AREA_PRINCIPAL = A.ID
WHERE C.ESTADO = 1
AND C.CULMINACION = "ACTUALMENTE";

CREATE VIEW LISTADO_CONTEOS_VISTA AS
WITH ALMACENX AS (
    SELECT 
        T.ID_PUNTO_OPERACION AS ID_TIENDA,
        PA.NOMBRE AS NOMBRE_ALMACEN
    FROM TIENDAS AS T
    INNER JOIN ALMACENES AS A ON T.ID_ALMACEN = A.ID
    INNER JOIN PUNTO_OPERACION AS PA ON PA.ID = A.ID_PUNTO_OPERACION
)
SELECT 
    L.ID AS ID,
    L.FECHA_INICIO,
    L.FECHA_FINAL,
    I.NOMBRE,
    O.NOMBRE AS REGISTRADO_POR,
    P.NOMBRE AS PUNTO_OPERACION,
    COALESCE(A.NOMBRE_ALMACEN, P.NOMBRE) AS ALMACEN, -- fallback si es un almacén directo
    P.TIPO,
    L.LINK_ARCHIVO_PDF
FROM LISTADO_CONTEOS AS L
INNER JOIN INVENTARIO AS I ON I.ID = L.ID_INVENTARIO
INNER JOIN PUNTO_OPERACION AS P ON P.ID = L.ID_PUNTO_OPERACION
INNER JOIN colaboradores AS O ON O.ID_PERSONA = L.REGISTRADO_POR_ID
LEFT JOIN ALMACENX AS A ON A.ID_TIENDA = P.ID
WHERE L.ESTADO = 1;

DROP VIEW IF EXISTS TIENDAS_VISTA;
CREATE VIEW TIENDAS_VISTA AS
with ALMACENX AS(
SELECT P.ID, P.NOMBRE FROM PUNTO_OPERACION AS P
INNER JOIN ALMACENES AS A
ON P.ID = A.ID_PUNTO_OPERACION
)
SELECT P.ID, P.NOMBRE, P.TIPO,X.NOMBRE AS ALMACEN FROM TIENDAS AS T
INNER JOIN PUNTO_OPERACION AS P
ON T.ID_PUNTO_OPERACION = P.ID
-- JOIN CON EL WITH
INNER JOIN ALMACENX AS X
ON X.ID = T.ID_ALMACEN
WHERE T.ESTADO = 1;

DROP PROCEDURE IF EXISTS COLABORADORES_PERMISOS;
DELIMITER $$;
CREATE PROCEDURE COLABORADORES_PERMISOS(IN METHOD VARCHAR(50))
BEGIN
	IF METHOD = "VISTA_INVENTARIO" THEN
		SELECT ID_PERSONA, NOMBRE 
        from colaboradores WHERE ID_ROL = 1;
	ELSEIF METHOD = "VISTA_CONTEO_INVENTARIO" THEN
		SELECT ID_PERSONA, NOMBRE FROM VISTA_PERMISOS_COLABORADORES
        WHERE ID_ROL in (1,2,3)
        AND AREA = "LOGISTICA";
	ELSEIF METHOD ="COLABORADORES_COMBO_AUDITORIA" THEN
		SELECT ID_PERSONA, NOMBRE FROM VISTA_PERMISOS_COLABORADORES
        WHERE ID_ROL in (1,2,3)
        AND AREA = "LOGISTICA" OR AREA = "ADMINISTRACION";
	ELSEIF METHOD = "TIENDAS_MALVINAS" then
		SELECT ID, NOMBRE FROM TIENDAS_VISTA
        WHERE TIPO = "TIENDA" AND ALMACEN = "MALVINAS";
	END IF;
END $$;
DELIMITER ;
CALL COLABORADORES_PERMISOS("COLABORADORES_COMBO_AUDITORIA");

DROP PROCEDURE IF EXISTS EXTRACCION_INVENTARIO;
DELIMITER $$;
CREATE PROCEDURE EXTRACCION_INVENTARIO(IN METHOD VARCHAR(50), IN VARIABLE VARCHAR(20))
BEGIN
    
	IF METhOD = "LISTAR_INVENTARIOS" THEN
		SELECT ID, NOMBRE FROM INVENTARIO ORDER BY FECHA_REGISTRO DESC LIMIT 10;
    ELSEIF METHOD = "LISTAR_INVENTARIOS_CONTEOS" THEN
        SELECT ID, FECHA_INICIO, FECHA_FINAL, NOMBRE AS INVENTARIO, REGISTRADO_POR AS NOMBRE, LINK_ARCHIVO_PDF, FECHA_FINAL, PUNTO_OPERACION
        FROM LISTADO_CONTEOS_VISTA
		WHERE ALMACEN = VARIABLE
        ORDER BY L.FECHA_FINAL DESC
        LIMIT 8;
    ELSEIF METHOD = "LISTAR_CONTEO_PUNTO_OPERACION" THEN
		SET @Inventario := (substring_index(VARIABLE,'-',1));
		SET @Almacen := (substring_index(VARIABLE,'-',-1));
		-- Get Json type data
		WITH PUNTOS AS (
			  SELECT PUNTO_OPERACION FROM LISTADO_CONTEOS_VISTA 
			  WHERE ALMACEN = @Almacen AND NOMBRE = @Inventario
			)
			SELECT 
			  L.NOMBRE,P.ID,P.CODIGO, P.NOMBRE AS PRODUCTO, SUM(DET.CANTIDAD) AS TOTAL, DET.UNIDAD_MEDIDA
			FROM LISTADO_CONTEOS_DETALLE AS DET
			INNER JOIN productos AS P
			  ON P.ID = DET.ID_PRODUCTOS
			INNER JOIN LISTADO_CONTEOS_VISTA AS L
			  ON L.ID = DET.ID_LISTADO_CONTEOS
			WHERE DET.ESTADO = 1
			  AND L.NOMBRE = @Inventario
			  AND L.PUNTO_OPERACION IN (SELECT PUNTO_OPERACION FROM PUNTOS)
			  AND L.ALMACEN = @Almacen
			GROUP BY L.NOMBRE, P.ID, P.NOMBRE, DET.UNIDAD_MEDIDA
			ORDER BY P.NOMBRE ASC;
	ELSEIF METHOD = "AUDITORIA_CONTEOS" THEN
		SET time_zone = "America/Lima";
		WITH PUNTOS AS(
		  SELECT ID,NOMBRE FROM PUNTO_OPERACION
		)
		SELECT AD.ID_INVENTARIO,AD.ID, PT.NOMBRE,AD.FECHA_REGISTRO, AD.CANTIDAD,AD.TIPO_ERROR, P.NOMBRE, AD.MOTIVO, R.NOMBRE AS REGISTRADO_POR, C.NOMBRE AS ERROR_DE, AD.OBSERVACIONES
			FROM AUDITORIA_COMPARACION AS AD
				INNER JOIN productos as P
				ON AD.ID_PRODUCTO = P.ID
				INNER JOIN colaboradores as R
				ON AD.REGISTRADO_POR_ID = R.ID_PERSONA
				INNER JOIN colaboradores as C
				ON AD.ERROR_ID = C.ID_PERSONA

        INNER JOIN PUNTOS AS PT
        ON PT.ID = AD.ID_PUNTO_OPERACION
			WHERE AD.ID_INVENTARIO = VARIABLE
			ORDER BY FECHA_REGISTRO ASC;
	ELSEIF METHOD= "INVENTARIO_EXCEL" THEN
			SET @ID_INVENTARIO := substring_index(VARIABLE,"-",1);
			SET @ID_ALMACEN := substring_index(VARIABLE, "-",-1);

			SELECT SK.ID, SK.ID_INVENTARIO, SK.TIPO_ALMACEN, DET.PRODUCTO, DET.CODIGO, DET.CANTIDAD, DET.ESTADO
			FROM STOCK_SISTEMA AS SK
			INNER JOIN STOCK_SISTEMA_DETALLE AS DET
			ON SK.ID = DET.ID_STOCK_SISTEMA
			WHERE SK.ESTADO = 1 AND SK.ID_INVENTARIO = @ID_INVENTARIO AND SK.TIPO_ALMACEN = @ID_ALMACEN
			AND DET.ESTADO = (SELECT MAX(DET.ESTADO) FROM STOCK_SISTEMA_DETALLE AS DET
							  INNER JOIN STOCK_SISTEMA AS SK
							  on DET.ID_STOCK_SISTEMA = SK.ID
							  WHERE SK.ID_INVENTARIO = @ID_INVENTARIO AND SK.TIPO_ALMACEN = @ID_ALMACEN
							  AND SK.ESTADO = 1)
			ORDER BY PRODUCTO ASC;
    END IF;
END $$;
DELIMITER ;
SELECT * FROM LISTADO_CONTEOS_VISTA;
CALL EXTRACCION_INVENTARIO('INVENTARIO_EXCEL','3-1');
CALL EXTRACCION_INVENTARIO('AUDITORIA_CONTEOS','3');
CALL EXTRACCION_INVENTARIO('LISTAR_CONTEO_PUNTO_OPERACION','OFICIAL-CALLAO');
SELECT substring_index('inven 01-TIENDA 3133','-', 1);
SELECT substring_index('1-2','-', 1);
#########################################################
-- TABLAS YA CREADAS
#########################################################
CREATE TABLE IF NOT EXISTS INVENTARIO(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(20) UNIQUE NOT NULL,
AREA VARCHAR(20) NOT NULL, #AMINISTRACION Y LOGISTICA
AUTORIZADO_POR INT NOT NULL REFERENCES colaboradores(ID_PERSONA) ,
FECHA_REGISTRO TIMESTAMP,
ESTADO CHAR(1) DEFAULT 1
);

CREATE TABLE PUNTO_OPERACION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    TIPO ENUM('ALMACEN', 'TIENDA') NOT NULL,
    UBICACION VARCHAR(150),
    FECHA_CREACION TIMESTAMP DEFAULT (DATE_SUB(NOW(), INTERVAL 5 HOUR)),
    ACTIVO CHAR(1) DEFAULT 1
);
SELECT * FROM PUNTO_OPERACION;
INSERT INTO PUNTO_OPERACION(NOMBRE, TIPO) VALUES
("MALVINAS",'ALMACEN'),("CALLAO",'ALMACEN'),
("TIENDA 3006",'TIENDA'), ("TIENDA 3006 B",'TIENDA'), ("TIENDA 3131",'TIENDA'), ("TIENDA 3133",'TIENDA'), ("TIENDA 412-A",'TIENDA');
CREATE TABLE IF NOT EXISTS TIENDAS(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_PUNTO_OPERACION INT REFERENCES PUNTO_OPERACION(ID),
ID_ALMACEN INT REFERENCES ALMACENES(ID),
CAPACIDAD_M3 DECIMAL(10,2),
ENCARGADO INT REFERENCES colaboradores(ID_PERSONA),
ESTADO CHAR(1) DEFAULT 1
);
INSERT INTO TIENDAS(ID_PUNTO_OPERACION,ID_ALMACEN) VALUES
(3,1), (4,1), (5,1), (6,1), (7,1);

CREATE TABLE IF NOT EXISTS ALMACENES(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_PUNTO_OPERACION INT REFERENCES PUNTO_OPERACION(ID),
UBICACION VARCHAR(150),
CANTIDAD INT DEFAULT 0,
ESTADO CHAR (1) DEFAULT 1
);
INSERT INTO ALMACENES(ID_PUNTO_OPERACION) VALUES (1),(2);

CREATE TABLE IF NOT EXISTS LISTADO_CONTEOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_INVENTARIO INT REFERENCES INVENTARIO(ID),
ID_PUNTO_OPERACION INT REFERENCES PUNTO_OPERACION(ID),
FECHA_INICIO TIMESTAMP NOT NULL,
FECHA_FINAL TIMESTAMP NOT NULL,
REGISTRADO_POR_ID INT NOT NULL REFERENCES colaboradores(ID_PERSONA),
LINK_ARCHIVO_PDF VARCHAR(255),
ESTADO CHAR(1) DEFAULT 1
);

CREATE TABLE IF NOT EXISTS LISTADO_CONTEOS_DETALLE(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_LISTADO_CONTEOS INT REFERENCES LISTADO_CONTEOS(ID),
ID_PRODUCTOS INT REFERENCES PRODUCTOS(ID),
CANTIDAD INT,
UNIDAD_MEDIDA VARCHAR(20),
ESTADO CHAR(1) DEFAULT 1
);



SET @Inventario := 'inven 01';
SET @Almacen := 'CALLAO';
  
WITH PUNTOS AS (
  SELECT PUNTO_OPERACION FROM LISTADO_CONTEOS_VISTA 
  WHERE ALMACEN = @Almacen AND NOMBRE = @Inventario
)
SELECT 
  L.NOMBRE,P.ID, P.NOMBRE AS PRODUCTO, SUM(DET.CANTIDAD) AS TOTAL, DET.UNIDAD_MEDIDA
FROM LISTADO_CONTEOS_DETALLE AS DET
INNER JOIN productos AS P
  ON P.ID = DET.ID_PRODUCTOS
INNER JOIN LISTADO_CONTEOS_VISTA AS L
  ON L.ID = DET.ID_LISTADO_CONTEOS
WHERE DET.ESTADO = 1
  AND L.NOMBRE = @Inventario
  AND L.PUNTO_OPERACION IN (SELECT PUNTO_OPERACION FROM PUNTOS)
  AND L.ALMACEN = @Almacen
GROUP BY 
  L.NOMBRE,
  P.ID,
  P.NOMBRE, 
  DET.UNIDAD_MEDIDA
ORDER BY P.NOMBRE ASC;
SELECT * FROM LISTADO_CONTEOS_VISTA;

#######################################
CREATE TABLE AUDITORIA_COMPARACION(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_INVENTARIO INT REFERENCES INVENTARIO(ID),
ID_PUNTO_OPERACION INT REFERENCES PUNTO_OPERACION(ID),
-- ID_LISTADO_CONTEO INT REFERENCES LISTADO_CONTEOS(ID),
CANTIDAD INT,
FECHA_REGISTRO TIMESTAMP NOT NULL,
TIPO_ERROR VARCHAR(30) NOT NULL,
ID_PRODUCTO INT REFERENCES productos (ID),
MOTIVO VARCHAR(30) NOT NULL,
REGISTRADO_POR_ID INT REFERENCES colaboradores(ID_PERSONA),
ERROR_ID INT REFERENCES colaboradores(ID_PERSONA),
OBSERVACIONES TEXT,
ESTADO CHAR(1) DEFAULT 1
);

## TRIGGER DE AUDITORIA DE COMPARACION
DROP TRIGGER IF EXISTS AUDITORIA_COMPARACION_TRIIGER_INSERT;
DELIMITER $$;
CREATE TRIGGER AUDITORIA_COMPARACION_TRIIGER_INSERT
AFTER INSERT ON AUDITORIA_COMPARACION
FOR EACH ROW
BEGIN
	UPDATE LISTADO_CONTEOS_DETALLE as L
    SET L.CANTIDAD = NEW.CANTIDAD
    WHERE L.ID_LISTADO_CONTEOS = (SELECT ID FROM LISTADO_CONTEOS 
								WHERE ID_INVENTARIO = NEW.ID_INVENTARIO
								AND ID_PUNTO_OPERACION = NEW.ID_PUNTO_OPERACION)
    AND L.ID_PRODUCTOS = NEW.ID_PRODUCTO;
END $$;
DELIMITER ;

DROP PROCEDURE IF EXISTS INSERT_JSON_INVENTARIO;
DELIMITER $$;
CREATE PROCEDURE INSERT_JSON_INVENTARIO(IN METHOD VARCHAR(30), IN DATOS JSON)
BEGIN
	SET time_zone = "America/Lima";
	IF METHOD = "AUDITORIA_COMPARACION" THEN
		INSERT INTO AUDITORIA_COMPARACION(ID_INVENTARIO, ID_PUNTO_OPERACION,CANTIDAD,FECHA_REGISTRO,TIPO_ERROR, ID_PRODUCTO, MOTIVO, REGISTRADO_POR_ID, ERROR_ID, OBSERVACIONES)
        VALUES(
			(SELECT DATOS->>'$.ID_INVENTARIO'),
            (select DATOS->>'$.ID_PUNTO_OPERACION'),
            (select DATOS->>'$.CANTIDAD'),
            (select NOW()),
            (SELECT DATOS->>'$.TIPO_ERROR'),
            (SELECT DATOS->>'$.ID_PRODUCTO'),
            (SELECT DATOS->>'$.MOTIVO'),
            (SELECT DATOS->>'$.REGISTRADO_POR_ID'),
            (SELECT DATOS->>'$.ERROR_ID'),
            (SELECT DATOS->>'$.OBSERVACIONES')
        );
	ELSEIF METHOD = "INSERTAR_INVENTARIO" THEN
		INSERT INTO INVENTARIO(NOMBRE, AREA, AUTORIZADO_POR, FECHA_REGISTRO)
		VALUES (
        (DATOS ->>'$.NOMBRE'), 
        (DATOS ->>'$.AREA'), 
        (DATOS ->>'$.AUTORIZADO_POR'),
        NOW());
    END IF;
END $$;
DELIMITER ;


CALL INSERT_JSON_INVENTARIO('AUDITORIA_COMPARACION',
'{
    "ID_INVENTARIO": "3",
    "ID_PUNTO_OPERACION": "2",
    "CANTIDAD": "44",
    "TIPO_ERROR": "SISTEMA",
    "ID_PRODUCTO": "1",
    "MOTIVO": "CONTEO MANUAL",
    "REGISTRADO_POR_ID": "4",
    "ERROR_ID": "1",
    "OBSERVACIONES": "no se que poner"
}');
SELECT * FROM AUDITORIA_COMPARACION;
TRUNCATE TABLE AUDITORIA_COMPARACION;
SET SQL_SAFE_UPDATES = 0;

WITH CONTEO_BASE AS (
SET @Inventario := 'OFICIAL';
SET @Almacen := 'CALLAO';
		-- Get Json type data
		WITH PUNTOS AS (
			  SELECT PUNTO_OPERACION FROM LISTADO_CONTEOS_VISTA 
			  WHERE ALMACEN = @Almacen AND NOMBRE = @Inventario
			)
			SELECT 
			  L.NOMBRE,P.ID,P.CODIGO, P.NOMBRE AS PRODUCTO, SUM(DET.CANTIDAD) AS TOTAL, DET.UNIDAD_MEDIDA
			FROM LISTADO_CONTEOS_DETALLE AS DET
			INNER JOIN productos AS P
			  ON P.ID = DET.ID_PRODUCTOS
			INNER JOIN LISTADO_CONTEOS_VISTA AS L
			  ON L.ID = DET.ID_LISTADO_CONTEOS
			WHERE DET.ESTADO = 1
			  AND L.NOMBRE = @Inventario
			  AND L.PUNTO_OPERACION IN (SELECT PUNTO_OPERACION FROM PUNTOS)
			  AND L.ALMACEN = @Almacen
			GROUP BY L.NOMBRE, P.ID, P.NOMBRE, DET.UNIDAD_MEDIDA
			ORDER BY P.NOMBRE ASC;
)
SELECT * FROM CONTEO_BASE AS CB

SELECT * FROM LISTADO_CONTEOS_VISTA;
CALL EXTRACCION_INVENTARIO('AUDITORIA_CONTEOS','3');

############################################
############################################
############################################
CREATE TABLE STOCK_SISTEMA(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_INVENTARIO INT REFERENCES INVENTARIO(ID),
TIPO_ALMACEN INT REFERENCES ALMACENES(ID),
ESTADO CHAR(1) DEFAULT 1 -- sumando mas números significa sus versiones
);
SELECT * FROM STOCK_SISTEMA;
DELETE FROM STOCK_SISTEMA WHERE ID=7;

CREATE TABLE STOCK_SISTEMA_DETALLE(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_STOCK_SISTEMA INT REFERENCES STOCK_SISTEMA(ID),
CANTIDAD INT NOT NULL,
PRODUCTO VARCHAR(70) NOT NULL,
CODIGO VARCHAR(30) NOT NULL,
ESTADO CHAR(1) DEFAULT 1 -- puede representar el numero de actualizaciones?
);
SELECT * FROM STOCK_SISTEMA_DETALLE;

DROP TRIGGER IF EXISTS UPDATE_STOCK_SISTEMA;
DELIMITER $$;
CREATE TRIGGER UPDATE_STOCK_SISTEMA
BEFORE INSERT ON STOCK_SISTEMA
FOR EACH ROW
BEGIN
	DECLARE VARIABLE VARCHAR(15);
    -- obtenemos un código único
    SELECT CONCAT(ID_INVENTARIO, "-",TIPO_ALMACEN) INTO VARIABLE 
	FROM STOCK_SISTEMA
	WHERE ID_INVENTARIO = NEW.ID_INVENTARIO AND TIPO_ALMACEN = NEW.TIPO_ALMACEN
    AND ESTADO = 1;
    
	IF VARIABLE = CONCAT(NEW.ID_INVENTARIO,"-",NEW.TIPO_ALMACEN) THEN
		UPDATE STOCK_SISTEMA_DETALLE SET ESTADO = ESTADO + 1
        WHERE ID_STOCK_SISTEMA = (SELECT ID FROM STOCK_SISTEMA 
								WHERE ID_INVENTARIO = NEW.ID_INVENTARIO
                                AND TIPO_ALMACEN = NEW.TIPO_ALMACEN);
		-- CALL ACTUALIZAR_STOCK_SISTEMA(NEW.ID_INVENTARIO,NEW.TIPO_ALMACEN);
    END IF;
END $$;
DELIMITER ;

DROP PROCEDURE IF EXISTS ACTUALIZAR_STOCK_SISTEMA;
DELIMITER $$;
CREATE PROCEDURE ACTUALIZAR_STOCK_SISTEMA(IN NEW_ID_INVENTARIO INT,IN NEW_TIPO_ALMACEN INT)
BEGIN
		DECLARE ID_EXCLUYENTE INT;
        SELECT MAX(ID) INTO ID_EXCLUYENTE FROM STOCK_SISTEMA
        WHERE ID_INVENTARIO = NEW_ID_INVENTARIO
        AND TIPO_ALMACEN = NEW_TIPO_ALMACEN;
	-- Actualizamos el anterior excel de datos 
        UPDATE STOCK_SISTEMA SET ESTADO = 0
        WHERE ID_INVENTARIO = NEW_ID_INVENTARIO
		AND TIPO_ALMACEN = NEW_TIPO_ALMACEN
        AND ID <> ID_EXCLUYENTE
        AND ESTADO = 1;
END $$;
DELIMITER ;
CALL ACTUALIZAR_STOCK_SISTEMA(3,2);

INSERT INTO STOCK_SISTEMA(ID_INVENTARIO, TIPO_ALMACEN)
VALUES (3, 2);
SET @id_stock := LAST_INSERT_ID();
INSERT INTO STOCK_SISTEMA_DETALLE(ID_STOCK_SISTEMA, CANTIDAD, PRODUCTO, CODIGO)
VALUES (@id_stock, 31, 'PAN', 'PAPAPA'),
(@id_stock, 21, 'QUESO', 'QUEQUEQUE');


SET @ID_INVENTARIO := 3;
SET @ID_ALMACEN := 2;

SELECT SK.ID, SK.ID_INVENTARIO, SK.TIPO_ALMACEN, DET.PRODUCTO, DET.CODIGO, DET.CANTIDAD, DET.ESTADO
FROM STOCK_SISTEMA AS SK
INNER JOIN STOCK_SISTEMA_DETALLE AS DET
ON SK.ID = DET.ID_STOCK_SISTEMA
WHERE SK.ESTADO = 1 AND SK.ID_INVENTARIO = @ID_INVENTARIO AND SK.TIPO_ALMACEN = @ID_ALMACEN
AND DET.ESTADO = (SELECT MAX(DET.ESTADO) FROM STOCK_SISTEMA_DETALLE AS DET
                  INNER JOIN STOCK_SISTEMA AS SK
                  on DET.ID_STOCK_SISTEMA = SK.ID
                  WHERE SK.ID_INVENTARIO = @ID_INVENTARIO AND SK.TIPO_ALMACEN = @ID_ALMACEN
                  AND SK.ESTADO = 1)
ORDER BY PRODUCTO ASC;