CREATE TABLE IF NOT EXISTS SIMULACION_PROFORMAS(
ID INT PRIMARY KEY AUTO_INCREMENT,
FECHA_REGISTRO TIMESTAMP,
ID_ASESOR INT REFERENCES colaboradores(ID_PERSONA),
ID_REGISTRADO_POR VARCHAR(50), -- REFERENCES colaboradores(ID_PERSONA),
ALMACEN INT REFERENCES ALMACENES(ID),
N_PROFORMA VARCHAR(20) NOT NULL UNIQUE,
ARCHIVO_URL VARCHAR(255),
ESTADO CHAR(1) DEFAULT 1
);

CREATE TABLE SIMULACION_PROFORMAS_DETALLE(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_SIMULACION_PROFORMA INT REFERENCES SIMULACION_PROFORMA(ID),
ID_PRODUCTO INT REFERENCES PRODUCTOS(ID),
UNIDAD_MEDIDA VARCHAR(25),
CANTIDAD INT NOT NULL,
ESTADO CHAR(1) DEFAULT 1
);
-- #########################################################
-- #########################################################
DROP PROCEDURE IF EXISTS COLABORADORES_PERMISOS;
DELIMITER $$;
CREATE PROCEDURE COLABORADORES_PERMISOS(IN METHOD VARCHAR(50))
BEGIN
	IF METHOD = "VISTA_INVENTARIO" THEN
		SELECT ID_PERSONA, NOMBRE 
        from colaboradores WHERE ID_ROL = 1;
	ELSEIF METHOD = "VISTA_CONTEO_INVENTARIO" THEN
		SELECT ID_PERSONA, NOMBRE FROM VISTA_PERMISOS_COLABORADORES
        WHERE ID_ROL in (1,2,3)
        AND AREA = "LOGISTICA";
	ELSEIF METHOD ="COLABORADORES_COMBO_AUDITORIA" THEN
		SELECT ID_PERSONA, NOMBRE FROM VISTA_PERMISOS_COLABORADORES
        WHERE ID_ROL in (1,2,3)
        AND AREA = "LOGISTICA" OR AREA = "ADMINISTRACION";
	ELSEIF METHOD = "TIENDAS_MALVINAS" then
		SELECT ID, NOMBRE FROM TIENDAS_VISTA
        WHERE TIPO = "TIENDA" AND ALMACEN = "MALVINAS";
	END IF;
END $$;
DELIMITER ;
CALL COLABORADORES_PERMISOS("COLABORADORES_COMBO_AUDITORIA");
-- #########################################################
-- #########################################################
DROP PROCEDURE IF EXISTS EXTRACCION_INVENTARIO;
DELIMITER $$;
CREATE PROCEDURE EXTRACCION_INVENTARIO(IN METHOD VARCHAR(50), IN VARIABLE VARCHAR(20))
BEGIN
    
	IF METhOD = "LISTAR_INVENTARIOS" THEN
		SELECT ID, NOMBRE FROM INVENTARIO ORDER BY FECHA_REGISTRO DESC LIMIT 10;
    ELSEIF METHOD = "LISTAR_INVENTARIOS_CONTEOS" THEN
        SELECT ID, FECHA_INICIO, FECHA_FINAL, NOMBRE AS INVENTARIO, REGISTRADO_POR AS NOMBRE, LINK_ARCHIVO_PDF, FECHA_FINAL, PUNTO_OPERACION
        FROM LISTADO_CONTEOS_VISTA
		WHERE ALMACEN = VARIABLE
        ORDER BY L.FECHA_FINAL DESC
        LIMIT 8;
    ELSEIF METHOD = "LISTAR_CONTEO_PUNTO_OPERACION" THEN
		SET @Inventario := (substring_index(VARIABLE,'-',1));
		SET @Almacen := (substring_index(VARIABLE,'-',-1));
		-- Get Json type data
		WITH PUNTOS AS (
			  SELECT PUNTO_OPERACION FROM LISTADO_CONTEOS_VISTA 
			  WHERE ALMACEN = @Almacen AND NOMBRE = @Inventario
			)
			SELECT 
			  L.NOMBRE,P.ID,P.CODIGO, P.NOMBRE AS PRODUCTO, SUM(DET.CANTIDAD) AS TOTAL, DET.UNIDAD_MEDIDA
			FROM LISTADO_CONTEOS_DETALLE AS DET
			INNER JOIN productos AS P
			  ON P.ID = DET.ID_PRODUCTOS
			INNER JOIN LISTADO_CONTEOS_VISTA AS L
			  ON L.ID = DET.ID_LISTADO_CONTEOS
			WHERE DET.ESTADO = 1
			  AND L.NOMBRE = @Inventario
			  AND L.PUNTO_OPERACION IN (SELECT PUNTO_OPERACION FROM PUNTOS)
			  AND L.ALMACEN = @Almacen
			GROUP BY L.NOMBRE, P.ID, P.NOMBRE, DET.UNIDAD_MEDIDA
			ORDER BY P.NOMBRE ASC;
	ELSEIF METHOD = "AUDITORIA_CONTEOS" THEN
		SET time_zone = "America/Lima";
		WITH PUNTOS AS(
		  SELECT ID,NOMBRE FROM PUNTO_OPERACION
		)
		SELECT AD.ID_INVENTARIO,AD.ID, PT.NOMBRE,AD.FECHA_REGISTRO, AD.CANTIDAD,AD.TIPO_ERROR, P.NOMBRE, AD.MOTIVO, R.NOMBRE AS REGISTRADO_POR, C.NOMBRE AS ERROR_DE, AD.OBSERVACIONES
			FROM AUDITORIA_COMPARACION AS AD
				INNER JOIN productos as P
				ON AD.ID_PRODUCTO = P.ID
				INNER JOIN colaboradores as R
				ON AD.REGISTRADO_POR_ID = R.ID_PERSONA
				INNER JOIN colaboradores as C
				ON AD.ERROR_ID = C.ID_PERSONA

        INNER JOIN PUNTOS AS PT
        ON PT.ID = AD.ID_PUNTO_OPERACION
			WHERE AD.ID_INVENTARIO = VARIABLE
			ORDER BY FECHA_REGISTRO ASC;
	ELSEIF METHOD= "INVENTARIO_EXCEL" THEN
			SET @ID_INVENTARIO := substring_index(VARIABLE,"-",1);
			SET @ID_ALMACEN := substring_index(VARIABLE, "-",-1);

			SELECT SK.ID, SK.ID_INVENTARIO, SK.TIPO_ALMACEN, DET.PRODUCTO, DET.CODIGO, DET.CANTIDAD, DET.ESTADO
			FROM STOCK_SISTEMA AS SK
			INNER JOIN STOCK_SISTEMA_DETALLE AS DET
			ON SK.ID = DET.ID_STOCK_SISTEMA
			WHERE SK.ESTADO = 1 AND SK.ID_INVENTARIO = @ID_INVENTARIO AND SK.TIPO_ALMACEN = @ID_ALMACEN
			AND DET.ESTADO = (SELECT MAX(DET.ESTADO) FROM STOCK_SISTEMA_DETALLE AS DET
							  INNER JOIN STOCK_SISTEMA AS SK
							  on DET.ID_STOCK_SISTEMA = SK.ID
							  WHERE SK.ID_INVENTARIO = @ID_INVENTARIO AND SK.TIPO_ALMACEN = @ID_ALMACEN
							  AND SK.ESTADO = 1)
			ORDER BY PRODUCTO ASC;
    END IF;
END $$;
DELIMITER ;
SELECT * FROM LISTADO_CONTEOS_VISTA;
CALL EXTRACCION_INVENTARIO('INVENTARIO_EXCEL','3-1');
CALL EXTRACCION_INVENTARIO('AUDITORIA_CONTEOS','3');
CALL EXTRACCION_INVENTARIO('LISTAR_CONTEO_PUNTO_OPERACION','OFICIAL-CALLAO');
SELECT substring_index('inven 01-TIENDA 3133','-', 1);
SELECT substring_index('1-2','-', 1);
-- #########################################################
-- #########################################################
SET @Inventario := 'inven 01';
SET @Almacen := 'CALLAO';
  
WITH PUNTOS AS (
  SELECT PUNTO_OPERACION FROM LISTADO_CONTEOS_VISTA 
  WHERE ALMACEN = @Almacen AND NOMBRE = @Inventario
)
SELECT 
  L.NOMBRE,P.ID, P.NOMBRE AS PRODUCTO, SUM(DET.CANTIDAD) AS TOTAL, DET.UNIDAD_MEDIDA
FROM LISTADO_CONTEOS_DETALLE AS DET
INNER JOIN productos AS P
  ON P.ID = DET.ID_PRODUCTOS
INNER JOIN LISTADO_CONTEOS_VISTA AS L
  ON L.ID = DET.ID_LISTADO_CONTEOS
WHERE DET.ESTADO = 1
  AND L.NOMBRE = @Inventario
  AND L.PUNTO_OPERACION IN (SELECT PUNTO_OPERACION FROM PUNTOS)
  AND L.ALMACEN = @Almacen
GROUP BY 
  L.NOMBRE,
  P.ID,
  P.NOMBRE, 
  DET.UNIDAD_MEDIDA
ORDER BY P.NOMBRE ASC;
SELECT * FROM LISTADO_CONTEOS_VISTA;

#######################################
DROP PROCEDURE IF EXISTS INSERT_JSON_INVENTARIO;
DELIMITER $$;
CREATE PROCEDURE INSERT_JSON_INVENTARIO(IN METHOD VARCHAR(30), IN DATOS JSON)
BEGIN
	SET time_zone = "America/Lima";
	IF METHOD = "AUDITORIA_COMPARACION" THEN
		INSERT INTO AUDITORIA_COMPARACION(ID_INVENTARIO, ID_PUNTO_OPERACION,CANTIDAD,FECHA_REGISTRO,TIPO_ERROR, ID_PRODUCTO, MOTIVO, REGISTRADO_POR_ID, ERROR_ID, OBSERVACIONES)
        VALUES(
			(SELECT DATOS->>'$.ID_INVENTARIO'),
            (select DATOS->>'$.ID_PUNTO_OPERACION'),
            (select DATOS->>'$.CANTIDAD'),
            (select NOW()),
            (SELECT DATOS->>'$.TIPO_ERROR'),
            (SELECT DATOS->>'$.ID_PRODUCTO'),
            (SELECT DATOS->>'$.MOTIVO'),
            (SELECT DATOS->>'$.REGISTRADO_POR_ID'),
            (SELECT DATOS->>'$.ERROR_ID'),
            (SELECT DATOS->>'$.OBSERVACIONES')
        );
	ELSEIF METHOD = "INSERTAR_INVENTARIO" THEN
		INSERT INTO INVENTARIO(NOMBRE, AREA, AUTORIZADO_POR, FECHA_REGISTRO)
		VALUES (
        (DATOS ->>'$.NOMBRE'), 
        (DATOS ->>'$.AREA'), 
        (DATOS ->>'$.AUTORIZADO_POR'),
        NOW());
    END IF;
END $$;
DELIMITER ;


CALL INSERT_JSON_INVENTARIO('AUDITORIA_COMPARACION',
'{
    "ID_INVENTARIO": "3",
    "ID_PUNTO_OPERACION": "2",
    "CANTIDAD": "44",
    "TIPO_ERROR": "SISTEMA",
    "ID_PRODUCTO": "1",
    "MOTIVO": "CONTEO MANUAL",
    "REGISTRADO_POR_ID": "4",
    "ERROR_ID": "1",
    "OBSERVACIONES": "no se que poner"
}');
SELECT * FROM AUDITORIA_COMPARACION;
TRUNCATE TABLE AUDITORIA_COMPARACION;
SET SQL_SAFE_UPDATES = 0;

WITH CONTEO_BASE AS (
SET @Inventario := 'OFICIAL';
SET @Almacen := 'CALLAO';
		-- Get Json type data
		WITH PUNTOS AS (
			  SELECT PUNTO_OPERACION FROM LISTADO_CONTEOS_VISTA 
			  WHERE ALMACEN = @Almacen AND NOMBRE = @Inventario
			)
			SELECT 
			  L.NOMBRE,P.ID,P.CODIGO, P.NOMBRE AS PRODUCTO, SUM(DET.CANTIDAD) AS TOTAL, DET.UNIDAD_MEDIDA
			FROM LISTADO_CONTEOS_DETALLE AS DET
			INNER JOIN productos AS P
			  ON P.ID = DET.ID_PRODUCTOS
			INNER JOIN LISTADO_CONTEOS_VISTA AS L
			  ON L.ID = DET.ID_LISTADO_CONTEOS
			WHERE DET.ESTADO = 1
			  AND L.NOMBRE = @Inventario
			  AND L.PUNTO_OPERACION IN (SELECT PUNTO_OPERACION FROM PUNTOS)
			  AND L.ALMACEN = @Almacen
			GROUP BY L.NOMBRE, P.ID, P.NOMBRE, DET.UNIDAD_MEDIDA
			ORDER BY P.NOMBRE ASC;
)
SELECT * FROM CONTEO_BASE AS CB

SELECT * FROM LISTADO_CONTEOS_VISTA;
CALL EXTRACCION_INVENTARIO('AUDITORIA_CONTEOS','3');
############################################
############################################
DROP PROCEDURE IF EXISTS ACTUALIZAR_STOCK_SISTEMA;
DELIMITER $$;
CREATE PROCEDURE ACTUALIZAR_STOCK_SISTEMA(IN NEW_ID_INVENTARIO INT,IN NEW_TIPO_ALMACEN INT)
BEGIN
		DECLARE ID_EXCLUYENTE INT;
        SELECT MAX(ID) INTO ID_EXCLUYENTE FROM STOCK_SISTEMA
        WHERE ID_INVENTARIO = NEW_ID_INVENTARIO
        AND TIPO_ALMACEN = NEW_TIPO_ALMACEN;
	-- Actualizamos el anterior excel de datos 
        UPDATE STOCK_SISTEMA SET ESTADO = 0
        WHERE ID_INVENTARIO = NEW_ID_INVENTARIO
		AND TIPO_ALMACEN = NEW_TIPO_ALMACEN
        AND ID <> ID_EXCLUYENTE
        AND ESTADO = 1;
END $$;
DELIMITER ;
CALL ACTUALIZAR_STOCK_SISTEMA(3,2);

INSERT INTO STOCK_SISTEMA(ID_INVENTARIO, TIPO_ALMACEN)
VALUES (3, 2);
SET @id_stock := LAST_INSERT_ID();
INSERT INTO STOCK_SISTEMA_DETALLE(ID_STOCK_SISTEMA, CANTIDAD, PRODUCTO, CODIGO)
VALUES (@id_stock, 31, 'PAN', 'PAPAPA'),
(@id_stock, 21, 'QUESO', 'QUEQUEQUE');

-- #########################################################
-- #########################################################
SET @ID_INVENTARIO := 3;
SET @ID_ALMACEN := 2;

SELECT SK.ID, SK.ID_INVENTARIO, SK.TIPO_ALMACEN, DET.PRODUCTO, DET.CODIGO, DET.CANTIDAD, DET.ESTADO
FROM STOCK_SISTEMA AS SK
INNER JOIN STOCK_SISTEMA_DETALLE AS DET
ON SK.ID = DET.ID_STOCK_SISTEMA
WHERE SK.ESTADO = 1 AND SK.ID_INVENTARIO = @ID_INVENTARIO AND SK.TIPO_ALMACEN = @ID_ALMACEN
AND DET.ESTADO = (SELECT MAX(DET.ESTADO) FROM STOCK_SISTEMA_DETALLE AS DET
                  INNER JOIN STOCK_SISTEMA AS SK
                  on DET.ID_STOCK_SISTEMA = SK.ID
                  WHERE SK.ID_INVENTARIO = @ID_INVENTARIO AND SK.TIPO_ALMACEN = @ID_ALMACEN
                  AND SK.ESTADO = 1)
ORDER BY PRODUCTO ASC;