## TRIGGER DE AUDITORIA DE COMPARACION
DROP TRIGGER IF EXISTS AUDITORIA_COMPARACION_TRIIGER_INSERT;
DELIMITER $$;
CREATE TRIGGER AUDITORIA_COMPARACION_TRIIGER_INSERT
AFTER INSERT ON AUDITORIA_COMPARACION
FOR EACH ROW
BEGIN
	UPDATE LISTADO_CONTEOS_DETALLE as L
    SET L.CANTIDAD = NEW.CANTIDAD
    WHERE L.ID_LISTADO_CONTEOS = (SELECT ID FROM LISTADO_CONTEOS 
								WHERE ID_INVENTARIO = NEW.ID_INVENTARIO
								AND ID_PUNTO_OPERACION = NEW.ID_PUNTO_OPERACION)
    AND L.ID_PRODUCTOS = NEW.ID_PRODUCTO;
END $$;
DELIMITER ;

DROP TRIGGER IF EXISTS UPDATE_STOCK_SISTEMA;
DELIMITER $$;
CREATE TRIGGER UPDATE_STOCK_SISTEMA
BEFORE INSERT ON STOCK_SISTEMA
FOR EACH ROW
BEGIN
	DECLARE VARIABLE VARCHAR(15);
    -- obtenemos un código único
    SELECT CONCAT(ID_INVENTARIO, "-",TIPO_ALMACEN) INTO VARIABLE 
	FROM STOCK_SISTEMA
	WHERE ID_INVENTARIO = NEW.ID_INVENTARIO AND TIPO_ALMACEN = NEW.TIPO_ALMACEN
    AND ESTADO = 1;
    
	IF VARIABLE = CONCAT(NEW.ID_INVENTARIO,"-",NEW.TIPO_ALMACEN) THEN
		UPDATE STOCK_SISTEMA_DETALLE SET ESTADO = ESTADO + 1
        WHERE ID_STOCK_SISTEMA = (SELECT ID FROM STOCK_SISTEMA 
								WHERE ID_INVENTARIO = NEW.ID_INVENTARIO
                                AND TIPO_ALMACEN = NEW.TIPO_ALMACEN);
		-- CALL ACTUALIZAR_STOCK_SISTEMA(NEW.ID_INVENTARIO,NEW.TIPO_ALMACEN);
    END IF;
END $$;
DELIMITER ;